version: "2"
linters:
  enable:
    - gocritic
    - godot
    - gosec
    - misspell
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
