version: "2"
linters:
  enable:
    - gocritic
    - godot
    - gosec
    - ineffassign
    - misspell
    - modernize
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    presets:
      - common-false-positives
formatters:
  enable:
    - gofumpt
