# Static linting of source files. See .golangci.yaml for options.
lint:
	golangci-lint run

# Discover all OS/ARCH platforms supported by the syscall package.
GOROOT := $(shell go env GOROOT)
SYSCALL_PLATFORMS := $(shell go tool dist list | tr '/' '_')

generate:
	go generate ./...
	@for plat in $(SYSCALL_PLATFORMS); do \
		os=$${plat%%_*}; arch=$${plat#*_}; \
		go run ./cmd/extract -gen -goos $$os -goarch $$arch \
			-o stdlib/syscall_$${plat}.go \
			syscall $(GOROOT)/src/syscall; \
	done

clean_generate:
	@grep -rl "Code generated by cmd/extract" stdlib/ | xargs rm -f

# Run tests with race detector, measure coverage.
test:
	go test -race -covermode=atomic -coverpkg=./... -coverprofile=cover.out ./interp

# Open coverage info in browser
cover: test
	go tool cover -html=cover.out
