// Code generated by "stringer -type=Op"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Add-1]
	_ = x[Addr-2]
	_ = x[Assign-3]
	_ = x[Fassign-4]
	_ = x[SetS-5]
	_ = x[Call-6]
	_ = x[CallX-7]
	_ = x[Deref-8]
	_ = x[Get-9]
	_ = x[Fnew-10]
	_ = x[FnewE-11]
	_ = x[Equal-12]
	_ = x[EqualSet-13]
	_ = x[Exit-14]
	_ = x[Field-15]
	_ = x[FieldE-16]
	_ = x[FieldSet-17]
	_ = x[FieldFset-18]
	_ = x[Greater-19]
	_ = x[Grow-20]
	_ = x[Index-21]
	_ = x[IndexSet-22]
	_ = x[Jump-23]
	_ = x[JumpTrue-24]
	_ = x[JumpFalse-25]
	_ = x[JumpSetTrue-26]
	_ = x[JumpSetFalse-27]
	_ = x[Len-28]
	_ = x[Lower-29]
	_ = x[MapIndex-30]
	_ = x[MapSet-31]
	_ = x[Mul-32]
	_ = x[New-33]
	_ = x[Negate-34]
	_ = x[Next-35]
	_ = x[Next2-36]
	_ = x[Not-37]
	_ = x[Pop-38]
	_ = x[Push-39]
	_ = x[Pull-40]
	_ = x[Pull2-41]
	_ = x[Return-42]
	_ = x[Set-43]
	_ = x[Slice-44]
	_ = x[Slice3-45]
	_ = x[Stop-46]
	_ = x[Sub-47]
	_ = x[Swap-48]
}

const _Op_name = "NopAddAddrAssignFassignSetSCallCallXDerefGetFnewFnewEEqualEqualSetExitFieldFieldEFieldSetFieldFsetGreaterGrowIndexIndexSetJumpJumpTrueJumpFalseJumpSetTrueJumpSetFalseLenLowerMapIndexMapSetMulNewNegateNextNext2NotPopPushPullPull2ReturnSetSliceSlice3StopSubSwap"

var _Op_index = [...]uint16{0, 3, 6, 10, 16, 23, 27, 31, 36, 41, 44, 48, 53, 58, 66, 70, 75, 81, 89, 98, 105, 109, 114, 122, 126, 134, 143, 154, 166, 169, 174, 182, 188, 191, 194, 200, 204, 209, 212, 215, 219, 223, 228, 234, 237, 242, 248, 252, 255, 259}

func (i Op) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
