// Code generated by "stringer -type=Op"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Add-1]
	_ = x[Addr-2]
	_ = x[Assign-3]
	_ = x[Fassign-4]
	_ = x[Vassign-5]
	_ = x[Call-6]
	_ = x[CallX-7]
	_ = x[Deref-8]
	_ = x[Dup-9]
	_ = x[Fdup-10]
	_ = x[Fnew-11]
	_ = x[FnewE-12]
	_ = x[Equal-13]
	_ = x[EqualSet-14]
	_ = x[Exit-15]
	_ = x[Field-16]
	_ = x[FieldE-17]
	_ = x[FieldSet-18]
	_ = x[FieldFset-19]
	_ = x[Greater-20]
	_ = x[Grow-21]
	_ = x[Index-22]
	_ = x[IndexSet-23]
	_ = x[Jump-24]
	_ = x[JumpTrue-25]
	_ = x[JumpFalse-26]
	_ = x[JumpSetTrue-27]
	_ = x[JumpSetFalse-28]
	_ = x[Len-29]
	_ = x[Lower-30]
	_ = x[MapIndex-31]
	_ = x[MapSet-32]
	_ = x[Mul-33]
	_ = x[New-34]
	_ = x[Negate-35]
	_ = x[Next-36]
	_ = x[Next2-37]
	_ = x[Not-38]
	_ = x[Pop-39]
	_ = x[Push-40]
	_ = x[Pull-41]
	_ = x[Pull2-42]
	_ = x[Return-43]
	_ = x[Slice-44]
	_ = x[Slice3-45]
	_ = x[Stop-46]
	_ = x[Sub-47]
	_ = x[Swap-48]
}

const _Op_name = "NopAddAddrAssignFassignVassignCallCallXDerefDupFdupFnewFnewEEqualEqualSetExitFieldFieldEFieldSetFieldFsetGreaterGrowIndexIndexSetJumpJumpTrueJumpFalseJumpSetTrueJumpSetFalseLenLowerMapIndexMapSetMulNewNegateNextNext2NotPopPushPullPull2ReturnSliceSlice3StopSubSwap"

var _Op_index = [...]uint16{0, 3, 6, 10, 16, 23, 30, 34, 39, 44, 47, 51, 55, 60, 65, 73, 77, 82, 88, 96, 105, 112, 116, 121, 129, 133, 141, 150, 161, 173, 176, 181, 189, 195, 198, 201, 207, 211, 216, 219, 222, 226, 230, 235, 241, 246, 252, 256, 259, 263}

func (i Op) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
