// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"archive/tar"
	"reflect"
)

func init() {
	Values["archive/tar"] = map[string]reflect.Value{
		"FileInfoHeader": reflect.ValueOf(tar.FileInfoHeader),
		"FormatGNU": reflect.ValueOf(tar.FormatGNU),
		"FormatPAX": reflect.ValueOf(tar.FormatPAX),
		"FormatUSTAR": reflect.ValueOf(tar.FormatUSTAR),
		"FormatUnknown": reflect.ValueOf(tar.FormatUnknown),
		"NewReader": reflect.ValueOf(tar.NewReader),
		"NewWriter": reflect.ValueOf(tar.NewWriter),
		"TypeBlock": reflect.ValueOf(tar.TypeBlock),
		"TypeChar": reflect.ValueOf(tar.TypeChar),
		"TypeCont": reflect.ValueOf(tar.TypeCont),
		"TypeDir": reflect.ValueOf(tar.TypeDir),
		"TypeFifo": reflect.ValueOf(tar.TypeFifo),
		"TypeGNULongLink": reflect.ValueOf(tar.TypeGNULongLink),
		"TypeGNULongName": reflect.ValueOf(tar.TypeGNULongName),
		"TypeGNUSparse": reflect.ValueOf(tar.TypeGNUSparse),
		"TypeLink": reflect.ValueOf(tar.TypeLink),
		"TypeReg": reflect.ValueOf(tar.TypeReg),
		"TypeRegA": reflect.ValueOf(tar.TypeRegA),
		"TypeSymlink": reflect.ValueOf(tar.TypeSymlink),
		"TypeXGlobalHeader": reflect.ValueOf(tar.TypeXGlobalHeader),
		"TypeXHeader": reflect.ValueOf(tar.TypeXHeader),
		"ErrFieldTooLong": reflect.ValueOf(&tar.ErrFieldTooLong),
		"ErrHeader": reflect.ValueOf(&tar.ErrHeader),
		"ErrInsecurePath": reflect.ValueOf(&tar.ErrInsecurePath),
		"ErrWriteAfterClose": reflect.ValueOf(&tar.ErrWriteAfterClose),
		"ErrWriteTooLong": reflect.ValueOf(&tar.ErrWriteTooLong),
		"FileInfoNames": reflect.ValueOf((*tar.FileInfoNames)(nil)),
		"Format": reflect.ValueOf((*tar.Format)(nil)),
		"Header": reflect.ValueOf((*tar.Header)(nil)),
		"Reader": reflect.ValueOf((*tar.Reader)(nil)),
		"Writer": reflect.ValueOf((*tar.Writer)(nil)),
	}
}
