// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"archive/zip"
	"reflect"
)

func init() {
	Values["archive/zip"] = map[string]reflect.Value{
		"Deflate": reflect.ValueOf(zip.Deflate),
		"OpenReader": reflect.ValueOf(zip.OpenReader),
		"Store": reflect.ValueOf(zip.Store),
		"ErrAlgorithm": reflect.ValueOf(&zip.ErrAlgorithm),
		"ErrChecksum": reflect.ValueOf(&zip.ErrChecksum),
		"ErrFormat": reflect.ValueOf(&zip.ErrFormat),
		"ErrInsecurePath": reflect.ValueOf(&zip.ErrInsecurePath),
		"File": reflect.ValueOf((*zip.File)(nil)),
		"FileHeader": reflect.ValueOf((*zip.FileHeader)(nil)),
		"ReadCloser": reflect.ValueOf((*zip.ReadCloser)(nil)),
		"Reader": reflect.ValueOf((*zip.Reader)(nil)),
		"Writer": reflect.ValueOf((*zip.Writer)(nil)),
	}
}
