// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"bufio"
	"reflect"
)

func init() {
	Values["bufio"] = map[string]reflect.Value{
		"MaxScanTokenSize": reflect.ValueOf(bufio.MaxScanTokenSize),
		"NewReadWriter": reflect.ValueOf(bufio.NewReadWriter),
		"NewReader": reflect.ValueOf(bufio.NewReader),
		"NewReaderSize": reflect.ValueOf(bufio.NewReaderSize),
		"NewScanner": reflect.ValueOf(bufio.NewScanner),
		"NewWriter": reflect.ValueOf(bufio.NewWriter),
		"NewWriterSize": reflect.ValueOf(bufio.NewWriterSize),
		"ScanBytes": reflect.ValueOf(bufio.ScanBytes),
		"ScanLines": reflect.ValueOf(bufio.ScanLines),
		"ScanRunes": reflect.ValueOf(bufio.ScanRunes),
		"ScanWords": reflect.ValueOf(bufio.ScanWords),
		"ErrAdvanceTooFar": reflect.ValueOf(&bufio.ErrAdvanceTooFar),
		"ErrBadReadCount": reflect.ValueOf(&bufio.ErrBadReadCount),
		"ErrBufferFull": reflect.ValueOf(&bufio.ErrBufferFull),
		"ErrFinalToken": reflect.ValueOf(&bufio.ErrFinalToken),
		"ErrInvalidUnreadByte": reflect.ValueOf(&bufio.ErrInvalidUnreadByte),
		"ErrInvalidUnreadRune": reflect.ValueOf(&bufio.ErrInvalidUnreadRune),
		"ErrNegativeAdvance": reflect.ValueOf(&bufio.ErrNegativeAdvance),
		"ErrNegativeCount": reflect.ValueOf(&bufio.ErrNegativeCount),
		"ErrTooLong": reflect.ValueOf(&bufio.ErrTooLong),
		"ReadWriter": reflect.ValueOf((*bufio.ReadWriter)(nil)),
		"Reader": reflect.ValueOf((*bufio.Reader)(nil)),
		"Scanner": reflect.ValueOf((*bufio.Scanner)(nil)),
		"SplitFunc": reflect.ValueOf((*bufio.SplitFunc)(nil)),
		"Writer": reflect.ValueOf((*bufio.Writer)(nil)),
	}
}
