// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"compress/lzw"
	"reflect"
)

func init() {
	Values["compress/lzw"] = map[string]reflect.Value{
		"LSB": reflect.ValueOf(lzw.LSB),
		"MSB": reflect.ValueOf(lzw.MSB),
		"Order": reflect.ValueOf((*lzw.Order)(nil)),
		"Reader": reflect.ValueOf((*lzw.Reader)(nil)),
		"Writer": reflect.ValueOf((*lzw.Writer)(nil)),
	}
}
