// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"compress/flate"
	"reflect"
)

func init() {
	Values["compress/flate"] = map[string]reflect.Value{
		"BestCompression": reflect.ValueOf(flate.BestCompression),
		"BestSpeed": reflect.ValueOf(flate.BestSpeed),
		"DefaultCompression": reflect.ValueOf(flate.DefaultCompression),
		"HuffmanOnly": reflect.ValueOf(flate.HuffmanOnly),
		"NewReader": reflect.ValueOf(flate.NewReader),
		"NewReaderDict": reflect.ValueOf(flate.NewReaderDict),
		"NewWriter": reflect.ValueOf(flate.NewWriter),
		"NewWriterDict": reflect.ValueOf(flate.NewWriterDict),
		"NoCompression": reflect.ValueOf(flate.NoCompression),
		"CorruptInputError": reflect.ValueOf((*flate.CorruptInputError)(nil)),
		"InternalError": reflect.ValueOf((*flate.InternalError)(nil)),
		"ReadError": reflect.ValueOf((*flate.ReadError)(nil)),
		"Reader": reflect.ValueOf((*flate.Reader)(nil)),
		"Resetter": reflect.ValueOf((*flate.Resetter)(nil)),
		"WriteError": reflect.ValueOf((*flate.WriteError)(nil)),
		"Writer": reflect.ValueOf((*flate.Writer)(nil)),
	}
}
