// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"compress/bzip2"
	"reflect"
)

func init() {
	Values["compress/bzip2"] = map[string]reflect.Value{
		"StructuralError": reflect.ValueOf((*bzip2.StructuralError)(nil)),
	}
}
