// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"compress/gzip"
	"reflect"
)

func init() {
	Values["compress/gzip"] = map[string]reflect.Value{
		"NoCompression": reflect.ValueOf(gzip.NoCompression),
		"ErrChecksum": reflect.ValueOf(&gzip.ErrChecksum),
		"ErrHeader": reflect.ValueOf(&gzip.ErrHeader),
		"Header": reflect.ValueOf((*gzip.Header)(nil)),
		"Reader": reflect.ValueOf((*gzip.Reader)(nil)),
		"Writer": reflect.ValueOf((*gzip.Writer)(nil)),
	}
}
