// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"container/list"
	"reflect"
)

func init() {
	Values["container/list"] = map[string]reflect.Value{
		"New": reflect.ValueOf(list.New),
		"Element": reflect.ValueOf((*list.Element)(nil)),
		"List": reflect.ValueOf((*list.List)(nil)),
	}
}
