// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"container/ring"
	"reflect"
)

func init() {
	Values["container/ring"] = map[string]reflect.Value{
		"New": reflect.ValueOf(ring.New),
		"Ring": reflect.ValueOf((*ring.Ring)(nil)),
	}
}
