// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"context"
	"reflect"
)

func init() {
	Values["context"] = map[string]reflect.Value{
		"AfterFunc": reflect.ValueOf(context.AfterFunc),
		"Background": reflect.ValueOf(context.Background),
		"Cause": reflect.ValueOf(context.Cause),
		"TODO": reflect.ValueOf(context.TODO),
		"WithCancel": reflect.ValueOf(context.WithCancel),
		"WithCancelCause": reflect.ValueOf(context.WithCancelCause),
		"WithValue": reflect.ValueOf(context.WithValue),
		"WithoutCancel": reflect.ValueOf(context.WithoutCancel),
		"Canceled": reflect.ValueOf(&context.Canceled),
		"DeadlineExceeded": reflect.ValueOf(&context.DeadlineExceeded),
		"CancelCauseFunc": reflect.ValueOf((*context.CancelCauseFunc)(nil)),
		"CancelFunc": reflect.ValueOf((*context.CancelFunc)(nil)),
		"Context": reflect.ValueOf((*context.Context)(nil)),
	}
}
