// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/elliptic"
	"reflect"
)

func init() {
	Values["crypto/elliptic"] = map[string]reflect.Value{
		"GenerateKey": reflect.ValueOf(elliptic.GenerateKey),
		"Marshal": reflect.ValueOf(elliptic.Marshal),
		"MarshalCompressed": reflect.ValueOf(elliptic.MarshalCompressed),
		"P224": reflect.ValueOf(elliptic.P224),
		"P256": reflect.ValueOf(elliptic.P256),
		"P384": reflect.ValueOf(elliptic.P384),
		"P521": reflect.ValueOf(elliptic.P521),
		"Unmarshal": reflect.ValueOf(elliptic.Unmarshal),
		"UnmarshalCompressed": reflect.ValueOf(elliptic.UnmarshalCompressed),
		"Curve": reflect.ValueOf((*elliptic.Curve)(nil)),
		"CurveParams": reflect.ValueOf((*elliptic.CurveParams)(nil)),
	}
}
