// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/md5"
	"reflect"
)

func init() {
	Values["crypto/md5"] = map[string]reflect.Value{
		"BlockSize": reflect.ValueOf(md5.BlockSize),
		"Size": reflect.ValueOf(md5.Size),
		"Sum": reflect.ValueOf(md5.Sum),
	}
}
