// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/ecdsa"
	"reflect"
)

func init() {
	Values["crypto/ecdsa"] = map[string]reflect.Value{
		"GenerateKey": reflect.ValueOf(ecdsa.GenerateKey),
		"ParseRawPrivateKey": reflect.ValueOf(ecdsa.ParseRawPrivateKey),
		"ParseUncompressedPublicKey": reflect.ValueOf(ecdsa.ParseUncompressedPublicKey),
		"SignASN1": reflect.ValueOf(ecdsa.SignASN1),
		"Verify": reflect.ValueOf(ecdsa.Verify),
		"VerifyASN1": reflect.ValueOf(ecdsa.VerifyASN1),
		"PrivateKey": reflect.ValueOf((*ecdsa.PrivateKey)(nil)),
		"PublicKey": reflect.ValueOf((*ecdsa.PublicKey)(nil)),
	}
}
