// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/fips140"
	"reflect"
)

func init() {
	Values["crypto/fips140"] = map[string]reflect.Value{
		"Enabled": reflect.ValueOf(fips140.Enabled),
		"Enforced": reflect.ValueOf(fips140.Enforced),
		"Version": reflect.ValueOf(fips140.Version),
		"WithoutEnforcement": reflect.ValueOf(fips140.WithoutEnforcement),
	}
}
