// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/ecdsa"
	"reflect"
)

func init() {
	Values["crypto/ecdsa"] = map[string]reflect.Value{
		"VerifyASN1": reflect.ValueOf(ecdsa.VerifyASN1),
		"PrivateKey": reflect.ValueOf((*ecdsa.PrivateKey)(nil)),
		"PublicKey": reflect.ValueOf((*ecdsa.PublicKey)(nil)),
	}
}
