// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/cipher"
	"reflect"
)

func init() {
	Values["crypto/cipher"] = map[string]reflect.Value{
		"NewCBCDecrypter": reflect.ValueOf(cipher.NewCBCDecrypter),
		"NewCBCEncrypter": reflect.ValueOf(cipher.NewCBCEncrypter),
		"NewCFBDecrypter": reflect.ValueOf(cipher.NewCFBDecrypter),
		"NewCFBEncrypter": reflect.ValueOf(cipher.NewCFBEncrypter),
		"NewCTR": reflect.ValueOf(cipher.NewCTR),
		"NewGCM": reflect.ValueOf(cipher.NewGCM),
		"NewGCMWithNonceSize": reflect.ValueOf(cipher.NewGCMWithNonceSize),
		"NewGCMWithRandomNonce": reflect.ValueOf(cipher.NewGCMWithRandomNonce),
		"NewGCMWithTagSize": reflect.ValueOf(cipher.NewGCMWithTagSize),
		"NewOFB": reflect.ValueOf(cipher.NewOFB),
		"AEAD": reflect.ValueOf((*cipher.AEAD)(nil)),
		"Block": reflect.ValueOf((*cipher.Block)(nil)),
		"BlockMode": reflect.ValueOf((*cipher.BlockMode)(nil)),
		"Stream": reflect.ValueOf((*cipher.Stream)(nil)),
		"StreamReader": reflect.ValueOf((*cipher.StreamReader)(nil)),
		"StreamWriter": reflect.ValueOf((*cipher.StreamWriter)(nil)),
	}
}
