// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/des"
	"reflect"
)

func init() {
	Values["crypto/des"] = map[string]reflect.Value{
		"BlockSize": reflect.ValueOf(des.BlockSize),
		"KeySizeError": reflect.ValueOf((*des.KeySizeError)(nil)),
	}
}
