// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/sha1"
	"reflect"
)

func init() {
	Values["crypto/sha1"] = map[string]reflect.Value{
		"BlockSize": reflect.ValueOf(sha1.BlockSize),
		"Size": reflect.ValueOf(sha1.Size),
		"Sum": reflect.ValueOf(sha1.Sum),
	}
}
