// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/hmac"
	"reflect"
)

func init() {
	Values["crypto/hmac"] = map[string]reflect.Value{
		"Equal": reflect.ValueOf(hmac.Equal),
	}
}
