// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/mlkem"
	"reflect"
)

func init() {
	Values["crypto/mlkem"] = map[string]reflect.Value{
		"CiphertextSize1024": reflect.ValueOf(mlkem.CiphertextSize1024),
		"CiphertextSize768": reflect.ValueOf(mlkem.CiphertextSize768),
		"EncapsulationKeySize1024": reflect.ValueOf(mlkem.EncapsulationKeySize1024),
		"EncapsulationKeySize768": reflect.ValueOf(mlkem.EncapsulationKeySize768),
		"GenerateKey1024": reflect.ValueOf(mlkem.GenerateKey1024),
		"GenerateKey768": reflect.ValueOf(mlkem.GenerateKey768),
		"NewDecapsulationKey1024": reflect.ValueOf(mlkem.NewDecapsulationKey1024),
		"NewDecapsulationKey768": reflect.ValueOf(mlkem.NewDecapsulationKey768),
		"NewEncapsulationKey1024": reflect.ValueOf(mlkem.NewEncapsulationKey1024),
		"NewEncapsulationKey768": reflect.ValueOf(mlkem.NewEncapsulationKey768),
		"SeedSize": reflect.ValueOf(mlkem.SeedSize),
		"SharedKeySize": reflect.ValueOf(mlkem.SharedKeySize),
		"DecapsulationKey1024": reflect.ValueOf((*mlkem.DecapsulationKey1024)(nil)),
		"DecapsulationKey768": reflect.ValueOf((*mlkem.DecapsulationKey768)(nil)),
		"EncapsulationKey1024": reflect.ValueOf((*mlkem.EncapsulationKey1024)(nil)),
		"EncapsulationKey768": reflect.ValueOf((*mlkem.EncapsulationKey768)(nil)),
	}
}
