// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/ecdh"
	"reflect"
)

func init() {
	Values["crypto/ecdh"] = map[string]reflect.Value{
		"P256": reflect.ValueOf(ecdh.P256),
		"P384": reflect.ValueOf(ecdh.P384),
		"P521": reflect.ValueOf(ecdh.P521),
		"X25519": reflect.ValueOf(ecdh.X25519),
		"Curve": reflect.ValueOf((*ecdh.Curve)(nil)),
		"KeyExchanger": reflect.ValueOf((*ecdh.KeyExchanger)(nil)),
		"PrivateKey": reflect.ValueOf((*ecdh.PrivateKey)(nil)),
		"PublicKey": reflect.ValueOf((*ecdh.PublicKey)(nil)),
	}
}
