// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/sha3"
	"reflect"
)

func init() {
	Values["crypto/sha3"] = map[string]reflect.Value{
		"New224": reflect.ValueOf(sha3.New224),
		"New256": reflect.ValueOf(sha3.New256),
		"New384": reflect.ValueOf(sha3.New384),
		"New512": reflect.ValueOf(sha3.New512),
		"NewCSHAKE128": reflect.ValueOf(sha3.NewCSHAKE128),
		"NewCSHAKE256": reflect.ValueOf(sha3.NewCSHAKE256),
		"NewSHAKE128": reflect.ValueOf(sha3.NewSHAKE128),
		"NewSHAKE256": reflect.ValueOf(sha3.NewSHAKE256),
		"Sum224": reflect.ValueOf(sha3.Sum224),
		"Sum256": reflect.ValueOf(sha3.Sum256),
		"Sum384": reflect.ValueOf(sha3.Sum384),
		"Sum512": reflect.ValueOf(sha3.Sum512),
		"SumSHAKE128": reflect.ValueOf(sha3.SumSHAKE128),
		"SumSHAKE256": reflect.ValueOf(sha3.SumSHAKE256),
		"SHA3": reflect.ValueOf((*sha3.SHA3)(nil)),
		"SHAKE": reflect.ValueOf((*sha3.SHAKE)(nil)),
	}
}
