// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/rc4"
	"reflect"
)

func init() {
	Values["crypto/rc4"] = map[string]reflect.Value{
		"NewCipher": reflect.ValueOf(rc4.NewCipher),
		"Cipher": reflect.ValueOf((*rc4.Cipher)(nil)),
		"KeySizeError": reflect.ValueOf((*rc4.KeySizeError)(nil)),
	}
}
