// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/aes"
	"reflect"
)

func init() {
	Values["crypto/aes"] = map[string]reflect.Value{
		"BlockSize": reflect.ValueOf(aes.BlockSize),
		"KeySizeError": reflect.ValueOf((*aes.KeySizeError)(nil)),
	}
}
