// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"crypto/rsa"
	"reflect"
)

func init() {
	Values["crypto/rsa"] = map[string]reflect.Value{
		"DecryptPKCS1v15": reflect.ValueOf(rsa.DecryptPKCS1v15),
		"DecryptPKCS1v15SessionKey": reflect.ValueOf(rsa.DecryptPKCS1v15SessionKey),
		"EncryptOAEPWithOptions": reflect.ValueOf(rsa.EncryptOAEPWithOptions),
		"EncryptPKCS1v15": reflect.ValueOf(rsa.EncryptPKCS1v15),
		"GenerateKey": reflect.ValueOf(rsa.GenerateKey),
		"GenerateMultiPrimeKey": reflect.ValueOf(rsa.GenerateMultiPrimeKey),
		"PSSSaltLengthAuto": reflect.ValueOf(rsa.PSSSaltLengthAuto),
		"PSSSaltLengthEqualsHash": reflect.ValueOf(rsa.PSSSaltLengthEqualsHash),
		"ErrDecryption": reflect.ValueOf(&rsa.ErrDecryption),
		"ErrMessageTooLong": reflect.ValueOf(&rsa.ErrMessageTooLong),
		"ErrVerification": reflect.ValueOf(&rsa.ErrVerification),
		"CRTValue": reflect.ValueOf((*rsa.CRTValue)(nil)),
		"OAEPOptions": reflect.ValueOf((*rsa.OAEPOptions)(nil)),
		"PKCS1v15DecryptOptions": reflect.ValueOf((*rsa.PKCS1v15DecryptOptions)(nil)),
		"PSSOptions": reflect.ValueOf((*rsa.PSSOptions)(nil)),
		"PrecomputedValues": reflect.ValueOf((*rsa.PrecomputedValues)(nil)),
		"PrivateKey": reflect.ValueOf((*rsa.PrivateKey)(nil)),
		"PublicKey": reflect.ValueOf((*rsa.PublicKey)(nil)),
	}
}
