// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"database/sql/driver"
	"reflect"
)

func init() {
	Values["database/sql/driver"] = map[string]reflect.Value{
		"IsScanValue": reflect.ValueOf(driver.IsScanValue),
		"IsValue": reflect.ValueOf(driver.IsValue),
		"Bool": reflect.ValueOf(&driver.Bool),
		"DefaultParameterConverter": reflect.ValueOf(&driver.DefaultParameterConverter),
		"ErrBadConn": reflect.ValueOf(&driver.ErrBadConn),
		"ErrRemoveArgument": reflect.ValueOf(&driver.ErrRemoveArgument),
		"ErrSkip": reflect.ValueOf(&driver.ErrSkip),
		"Int32": reflect.ValueOf(&driver.Int32),
		"ResultNoRows": reflect.ValueOf(&driver.ResultNoRows),
		"String": reflect.ValueOf(&driver.String),
		"ColumnConverter": reflect.ValueOf((*driver.ColumnConverter)(nil)),
		"Conn": reflect.ValueOf((*driver.Conn)(nil)),
		"ConnBeginTx": reflect.ValueOf((*driver.ConnBeginTx)(nil)),
		"ConnPrepareContext": reflect.ValueOf((*driver.ConnPrepareContext)(nil)),
		"Connector": reflect.ValueOf((*driver.Connector)(nil)),
		"Driver": reflect.ValueOf((*driver.Driver)(nil)),
		"DriverContext": reflect.ValueOf((*driver.DriverContext)(nil)),
		"Execer": reflect.ValueOf((*driver.Execer)(nil)),
		"ExecerContext": reflect.ValueOf((*driver.ExecerContext)(nil)),
		"IsolationLevel": reflect.ValueOf((*driver.IsolationLevel)(nil)),
		"NamedValue": reflect.ValueOf((*driver.NamedValue)(nil)),
		"NamedValueChecker": reflect.ValueOf((*driver.NamedValueChecker)(nil)),
		"NotNull": reflect.ValueOf((*driver.NotNull)(nil)),
		"Null": reflect.ValueOf((*driver.Null)(nil)),
		"Pinger": reflect.ValueOf((*driver.Pinger)(nil)),
		"Queryer": reflect.ValueOf((*driver.Queryer)(nil)),
		"QueryerContext": reflect.ValueOf((*driver.QueryerContext)(nil)),
		"Result": reflect.ValueOf((*driver.Result)(nil)),
		"Rows": reflect.ValueOf((*driver.Rows)(nil)),
		"RowsAffected": reflect.ValueOf((*driver.RowsAffected)(nil)),
		"RowsColumnTypeDatabaseTypeName": reflect.ValueOf((*driver.RowsColumnTypeDatabaseTypeName)(nil)),
		"RowsColumnTypeLength": reflect.ValueOf((*driver.RowsColumnTypeLength)(nil)),
		"RowsColumnTypeNullable": reflect.ValueOf((*driver.RowsColumnTypeNullable)(nil)),
		"RowsColumnTypePrecisionScale": reflect.ValueOf((*driver.RowsColumnTypePrecisionScale)(nil)),
		"RowsColumnTypeScanType": reflect.ValueOf((*driver.RowsColumnTypeScanType)(nil)),
		"RowsNextResultSet": reflect.ValueOf((*driver.RowsNextResultSet)(nil)),
		"SessionResetter": reflect.ValueOf((*driver.SessionResetter)(nil)),
		"Stmt": reflect.ValueOf((*driver.Stmt)(nil)),
		"StmtExecContext": reflect.ValueOf((*driver.StmtExecContext)(nil)),
		"StmtQueryContext": reflect.ValueOf((*driver.StmtQueryContext)(nil)),
		"Tx": reflect.ValueOf((*driver.Tx)(nil)),
		"TxOptions": reflect.ValueOf((*driver.TxOptions)(nil)),
		"Validator": reflect.ValueOf((*driver.Validator)(nil)),
		"Value": reflect.ValueOf((*driver.Value)(nil)),
		"ValueConverter": reflect.ValueOf((*driver.ValueConverter)(nil)),
		"Valuer": reflect.ValueOf((*driver.Valuer)(nil)),
	}
}
