// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"database/sql"
	"reflect"
)

func init() {
	Values["database/sql"] = map[string]reflect.Value{
		"Drivers": reflect.ValueOf(sql.Drivers),
		"LevelDefault": reflect.ValueOf(sql.LevelDefault),
		"LevelLinearizable": reflect.ValueOf(sql.LevelLinearizable),
		"LevelReadCommitted": reflect.ValueOf(sql.LevelReadCommitted),
		"LevelReadUncommitted": reflect.ValueOf(sql.LevelReadUncommitted),
		"LevelRepeatableRead": reflect.ValueOf(sql.LevelRepeatableRead),
		"LevelSerializable": reflect.ValueOf(sql.LevelSerializable),
		"LevelSnapshot": reflect.ValueOf(sql.LevelSnapshot),
		"LevelWriteCommitted": reflect.ValueOf(sql.LevelWriteCommitted),
		"Named": reflect.ValueOf(sql.Named),
		"Open": reflect.ValueOf(sql.Open),
		"OpenDB": reflect.ValueOf(sql.OpenDB),
		"ErrConnDone": reflect.ValueOf(&sql.ErrConnDone),
		"ErrNoRows": reflect.ValueOf(&sql.ErrNoRows),
		"ErrTxDone": reflect.ValueOf(&sql.ErrTxDone),
		"ColumnType": reflect.ValueOf((*sql.ColumnType)(nil)),
		"Conn": reflect.ValueOf((*sql.Conn)(nil)),
		"DB": reflect.ValueOf((*sql.DB)(nil)),
		"DBStats": reflect.ValueOf((*sql.DBStats)(nil)),
		"IsolationLevel": reflect.ValueOf((*sql.IsolationLevel)(nil)),
		"NamedArg": reflect.ValueOf((*sql.NamedArg)(nil)),
		"NullBool": reflect.ValueOf((*sql.NullBool)(nil)),
		"NullByte": reflect.ValueOf((*sql.NullByte)(nil)),
		"NullFloat64": reflect.ValueOf((*sql.NullFloat64)(nil)),
		"NullInt16": reflect.ValueOf((*sql.NullInt16)(nil)),
		"NullInt32": reflect.ValueOf((*sql.NullInt32)(nil)),
		"NullInt64": reflect.ValueOf((*sql.NullInt64)(nil)),
		"NullString": reflect.ValueOf((*sql.NullString)(nil)),
		"NullTime": reflect.ValueOf((*sql.NullTime)(nil)),
		"Out": reflect.ValueOf((*sql.Out)(nil)),
		"RawBytes": reflect.ValueOf((*sql.RawBytes)(nil)),
		"Result": reflect.ValueOf((*sql.Result)(nil)),
		"Row": reflect.ValueOf((*sql.Row)(nil)),
		"Rows": reflect.ValueOf((*sql.Rows)(nil)),
		"Scanner": reflect.ValueOf((*sql.Scanner)(nil)),
		"Stmt": reflect.ValueOf((*sql.Stmt)(nil)),
		"Tx": reflect.ValueOf((*sql.Tx)(nil)),
		"TxOptions": reflect.ValueOf((*sql.TxOptions)(nil)),
	}
}
