// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"debug/buildinfo"
	"reflect"
)

func init() {
	Values["debug/buildinfo"] = map[string]reflect.Value{
		"Read": reflect.ValueOf(buildinfo.Read),
		"ReadFile": reflect.ValueOf(buildinfo.ReadFile),
		"BuildInfo": reflect.ValueOf((*buildinfo.BuildInfo)(nil)),
	}
}
