// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"embed"
	"reflect"
)

func init() {
	Values["embed"] = map[string]reflect.Value{
		"FS": reflect.ValueOf((*embed.FS)(nil)),
	}
}
