// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/pem"
	"reflect"
)

func init() {
	Values["encoding/pem"] = map[string]reflect.Value{
		"Decode": reflect.ValueOf(pem.Decode),
		"EncodeToMemory": reflect.ValueOf(pem.EncodeToMemory),
		"Block": reflect.ValueOf((*pem.Block)(nil)),
	}
}
