// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/csv"
	"reflect"
)

func init() {
	Values["encoding/csv"] = map[string]reflect.Value{
		"ErrBareQuote": reflect.ValueOf(&csv.ErrBareQuote),
		"ErrFieldCount": reflect.ValueOf(&csv.ErrFieldCount),
		"ErrQuote": reflect.ValueOf(&csv.ErrQuote),
		"ErrTrailingComma": reflect.ValueOf(&csv.ErrTrailingComma),
		"ParseError": reflect.ValueOf((*csv.ParseError)(nil)),
		"Reader": reflect.ValueOf((*csv.Reader)(nil)),
		"Writer": reflect.ValueOf((*csv.Writer)(nil)),
	}
}
