// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding"
	"reflect"
)

func init() {
	Values["encoding"] = map[string]reflect.Value{
		"BinaryAppender": reflect.ValueOf((*encoding.BinaryAppender)(nil)),
		"BinaryMarshaler": reflect.ValueOf((*encoding.BinaryMarshaler)(nil)),
		"BinaryUnmarshaler": reflect.ValueOf((*encoding.BinaryUnmarshaler)(nil)),
		"TextAppender": reflect.ValueOf((*encoding.TextAppender)(nil)),
		"TextMarshaler": reflect.ValueOf((*encoding.TextMarshaler)(nil)),
		"TextUnmarshaler": reflect.ValueOf((*encoding.TextUnmarshaler)(nil)),
	}
}
