// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/hex"
	"reflect"
)

func init() {
	Values["encoding/hex"] = map[string]reflect.Value{
		"AppendDecode": reflect.ValueOf(hex.AppendDecode),
		"AppendEncode": reflect.ValueOf(hex.AppendEncode),
		"Decode": reflect.ValueOf(hex.Decode),
		"DecodeString": reflect.ValueOf(hex.DecodeString),
		"DecodedLen": reflect.ValueOf(hex.DecodedLen),
		"Dump": reflect.ValueOf(hex.Dump),
		"Encode": reflect.ValueOf(hex.Encode),
		"EncodeToString": reflect.ValueOf(hex.EncodeToString),
		"EncodedLen": reflect.ValueOf(hex.EncodedLen),
		"ErrLength": reflect.ValueOf(&hex.ErrLength),
		"InvalidByteError": reflect.ValueOf((*hex.InvalidByteError)(nil)),
	}
}
