// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/base32"
	"reflect"
)

func init() {
	Values["encoding/base32"] = map[string]reflect.Value{
		"NewEncoding": reflect.ValueOf(base32.NewEncoding),
		"NoPadding": reflect.ValueOf(base32.NoPadding),
		"StdPadding": reflect.ValueOf(base32.StdPadding),
		"HexEncoding": reflect.ValueOf(&base32.HexEncoding),
		"StdEncoding": reflect.ValueOf(&base32.StdEncoding),
		"CorruptInputError": reflect.ValueOf((*base32.CorruptInputError)(nil)),
		"Encoding": reflect.ValueOf((*base32.Encoding)(nil)),
	}
}
