// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/xml"
	"reflect"
)

func init() {
	Values["encoding/xml"] = map[string]reflect.Value{
		"CopyToken": reflect.ValueOf(xml.CopyToken),
		"Escape": reflect.ValueOf(xml.Escape),
		"EscapeText": reflect.ValueOf(xml.EscapeText),
		"Header": reflect.ValueOf(xml.Header),
		"Marshal": reflect.ValueOf(xml.Marshal),
		"MarshalIndent": reflect.ValueOf(xml.MarshalIndent),
		"NewDecoder": reflect.ValueOf(xml.NewDecoder),
		"NewEncoder": reflect.ValueOf(xml.NewEncoder),
		"NewTokenDecoder": reflect.ValueOf(xml.NewTokenDecoder),
		"Unmarshal": reflect.ValueOf(xml.Unmarshal),
		"HTMLAutoClose": reflect.ValueOf(&xml.HTMLAutoClose),
		"HTMLEntity": reflect.ValueOf(&xml.HTMLEntity),
		"Attr": reflect.ValueOf((*xml.Attr)(nil)),
		"CharData": reflect.ValueOf((*xml.CharData)(nil)),
		"Comment": reflect.ValueOf((*xml.Comment)(nil)),
		"Decoder": reflect.ValueOf((*xml.Decoder)(nil)),
		"Directive": reflect.ValueOf((*xml.Directive)(nil)),
		"Encoder": reflect.ValueOf((*xml.Encoder)(nil)),
		"EndElement": reflect.ValueOf((*xml.EndElement)(nil)),
		"Marshaler": reflect.ValueOf((*xml.Marshaler)(nil)),
		"MarshalerAttr": reflect.ValueOf((*xml.MarshalerAttr)(nil)),
		"Name": reflect.ValueOf((*xml.Name)(nil)),
		"ProcInst": reflect.ValueOf((*xml.ProcInst)(nil)),
		"StartElement": reflect.ValueOf((*xml.StartElement)(nil)),
		"SyntaxError": reflect.ValueOf((*xml.SyntaxError)(nil)),
		"TagPathError": reflect.ValueOf((*xml.TagPathError)(nil)),
		"Token": reflect.ValueOf((*xml.Token)(nil)),
		"TokenReader": reflect.ValueOf((*xml.TokenReader)(nil)),
		"UnmarshalError": reflect.ValueOf((*xml.UnmarshalError)(nil)),
		"Unmarshaler": reflect.ValueOf((*xml.Unmarshaler)(nil)),
		"UnmarshalerAttr": reflect.ValueOf((*xml.UnmarshalerAttr)(nil)),
		"UnsupportedTypeError": reflect.ValueOf((*xml.UnsupportedTypeError)(nil)),
	}
}
