// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/binary"
	"reflect"
)

func init() {
	Values["encoding/binary"] = map[string]reflect.Value{
		"Append": reflect.ValueOf(binary.Append),
		"AppendUvarint": reflect.ValueOf(binary.AppendUvarint),
		"AppendVarint": reflect.ValueOf(binary.AppendVarint),
		"Decode": reflect.ValueOf(binary.Decode),
		"Encode": reflect.ValueOf(binary.Encode),
		"MaxVarintLen16": reflect.ValueOf(binary.MaxVarintLen16),
		"MaxVarintLen32": reflect.ValueOf(binary.MaxVarintLen32),
		"MaxVarintLen64": reflect.ValueOf(binary.MaxVarintLen64),
		"PutUvarint": reflect.ValueOf(binary.PutUvarint),
		"PutVarint": reflect.ValueOf(binary.PutVarint),
		"Read": reflect.ValueOf(binary.Read),
		"ReadUvarint": reflect.ValueOf(binary.ReadUvarint),
		"ReadVarint": reflect.ValueOf(binary.ReadVarint),
		"Size": reflect.ValueOf(binary.Size),
		"Uvarint": reflect.ValueOf(binary.Uvarint),
		"Varint": reflect.ValueOf(binary.Varint),
		"Write": reflect.ValueOf(binary.Write),
		"BigEndian": reflect.ValueOf(&binary.BigEndian),
		"LittleEndian": reflect.ValueOf(&binary.LittleEndian),
		"NativeEndian": reflect.ValueOf(&binary.NativeEndian),
		"AppendByteOrder": reflect.ValueOf((*binary.AppendByteOrder)(nil)),
		"ByteOrder": reflect.ValueOf((*binary.ByteOrder)(nil)),
	}
}
