// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"encoding/ascii85"
	"reflect"
)

func init() {
	Values["encoding/ascii85"] = map[string]reflect.Value{
		"Decode": reflect.ValueOf(ascii85.Decode),
		"Encode": reflect.ValueOf(ascii85.Encode),
		"MaxEncodedLen": reflect.ValueOf(ascii85.MaxEncodedLen),
		"CorruptInputError": reflect.ValueOf((*ascii85.CorruptInputError)(nil)),
	}
}
