// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"errors"
	"reflect"
)

func init() {
	Values["errors"] = map[string]reflect.Value{
		"As": reflect.ValueOf(errors.As),
		"Is": reflect.ValueOf(errors.Is),
		"Join": reflect.ValueOf(errors.Join),
		"New": reflect.ValueOf(errors.New),
		"Unwrap": reflect.ValueOf(errors.Unwrap),
		"ErrUnsupported": reflect.ValueOf(&errors.ErrUnsupported),
	}
}
