// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"expvar"
	"reflect"
)

func init() {
	Values["expvar"] = map[string]reflect.Value{
		"Do": reflect.ValueOf(expvar.Do),
		"Get": reflect.ValueOf(expvar.Get),
		"NewFloat": reflect.ValueOf(expvar.NewFloat),
		"NewInt": reflect.ValueOf(expvar.NewInt),
		"NewMap": reflect.ValueOf(expvar.NewMap),
		"NewString": reflect.ValueOf(expvar.NewString),
		"Publish": reflect.ValueOf(expvar.Publish),
		"Float": reflect.ValueOf((*expvar.Float)(nil)),
		"Func": reflect.ValueOf((*expvar.Func)(nil)),
		"Int": reflect.ValueOf((*expvar.Int)(nil)),
		"KeyValue": reflect.ValueOf((*expvar.KeyValue)(nil)),
		"Map": reflect.ValueOf((*expvar.Map)(nil)),
		"String": reflect.ValueOf((*expvar.String)(nil)),
		"Var": reflect.ValueOf((*expvar.Var)(nil)),
	}
}
