// Code generation directive for stdlib bindings.
// Run "go generate ./stdlib" to regenerate all binding files.

package stdlib

//go:generate go run ../cmd/extract -gen -o archive_tar.go archive/tar $GOROOT/src/archive/tar
//go:generate go run ../cmd/extract -gen -o archive_zip.go archive/zip $GOROOT/src/archive/zip
//go:generate go run ../cmd/extract -gen -o bufio.go bufio $GOROOT/src/bufio
//go:generate go run ../cmd/extract -gen -o bytes.go bytes $GOROOT/src/bytes
//go:generate go run ../cmd/extract -gen -o compress_bzip2.go compress/bzip2 $GOROOT/src/compress/bzip2
//go:generate go run ../cmd/extract -gen -o compress_flate.go compress/flate $GOROOT/src/compress/flate
//go:generate go run ../cmd/extract -gen -o compress_gzip.go compress/gzip $GOROOT/src/compress/gzip
//go:generate go run ../cmd/extract -gen -o compress_lzw.go compress/lzw $GOROOT/src/compress/lzw
//go:generate go run ../cmd/extract -gen -o compress_zlib.go compress/zlib $GOROOT/src/compress/zlib
//go:generate go run ../cmd/extract -gen -o container_heap.go container/heap $GOROOT/src/container/heap
//go:generate go run ../cmd/extract -gen -o container_list.go container/list $GOROOT/src/container/list
//go:generate go run ../cmd/extract -gen -o container_ring.go container/ring $GOROOT/src/container/ring
//go:generate go run ../cmd/extract -gen -o context.go context $GOROOT/src/context
//go:generate go run ../cmd/extract -gen -o crypto.go crypto $GOROOT/src/crypto
//go:generate go run ../cmd/extract -gen -o crypto_aes.go crypto/aes $GOROOT/src/crypto/aes
//go:generate go run ../cmd/extract -gen -o crypto_cipher.go crypto/cipher $GOROOT/src/crypto/cipher
//go:generate go run ../cmd/extract -gen -o crypto_des.go crypto/des $GOROOT/src/crypto/des
//go:generate go run ../cmd/extract -gen -o crypto_dsa.go crypto/dsa $GOROOT/src/crypto/dsa
//go:generate go run ../cmd/extract -gen -o crypto_ecdh.go crypto/ecdh $GOROOT/src/crypto/ecdh
//go:generate go run ../cmd/extract -gen -o crypto_ecdsa.go crypto/ecdsa $GOROOT/src/crypto/ecdsa
//go:generate go run ../cmd/extract -gen -o crypto_ed25519.go crypto/ed25519 $GOROOT/src/crypto/ed25519
//go:generate go run ../cmd/extract -gen -o crypto_elliptic.go crypto/elliptic $GOROOT/src/crypto/elliptic
//go:generate go run ../cmd/extract -gen -o crypto_fips140.go crypto/fips140 $GOROOT/src/crypto/fips140
//go:generate go run ../cmd/extract -gen -o crypto_hmac.go crypto/hmac $GOROOT/src/crypto/hmac
//go:generate go run ../cmd/extract -gen -o crypto_hpke.go crypto/hpke $GOROOT/src/crypto/hpke
//go:generate go run ../cmd/extract -gen -o crypto_md5.go crypto/md5 $GOROOT/src/crypto/md5
//go:generate go run ../cmd/extract -gen -o crypto_mlkem.go crypto/mlkem $GOROOT/src/crypto/mlkem
//go:generate go run ../cmd/extract -gen -o crypto_rand.go crypto/rand $GOROOT/src/crypto/rand
//go:generate go run ../cmd/extract -gen -o crypto_rc4.go crypto/rc4 $GOROOT/src/crypto/rc4
//go:generate go run ../cmd/extract -gen -o crypto_rsa.go crypto/rsa $GOROOT/src/crypto/rsa
//go:generate go run ../cmd/extract -gen -o crypto_sha1.go crypto/sha1 $GOROOT/src/crypto/sha1
//go:generate go run ../cmd/extract -gen -o crypto_sha256.go crypto/sha256 $GOROOT/src/crypto/sha256
//go:generate go run ../cmd/extract -gen -o crypto_sha3.go crypto/sha3 $GOROOT/src/crypto/sha3
//go:generate go run ../cmd/extract -gen -o crypto_sha512.go crypto/sha512 $GOROOT/src/crypto/sha512
//go:generate go run ../cmd/extract -gen -o crypto_subtle.go crypto/subtle $GOROOT/src/crypto/subtle
//go:generate go run ../cmd/extract -gen -o crypto_tls.go crypto/tls $GOROOT/src/crypto/tls
//go:generate go run ../cmd/extract -gen -o crypto_x509.go crypto/x509 $GOROOT/src/crypto/x509
//go:generate go run ../cmd/extract -gen -o crypto_x509_pkix.go crypto/x509/pkix $GOROOT/src/crypto/x509/pkix
//go:generate go run ../cmd/extract -gen -o database_sql.go database/sql $GOROOT/src/database/sql
//go:generate go run ../cmd/extract -gen -o database_sql_driver.go database/sql/driver $GOROOT/src/database/sql/driver
//go:generate go run ../cmd/extract -gen -o debug_dwarf.go debug/dwarf $GOROOT/src/debug/dwarf
//go:generate go run ../cmd/extract -gen -o debug_elf.go debug/elf $GOROOT/src/debug/elf
//go:generate go run ../cmd/extract -gen -o debug_gosym.go debug/gosym $GOROOT/src/debug/gosym
//go:generate go run ../cmd/extract -gen -o debug_macho.go debug/macho $GOROOT/src/debug/macho
//go:generate go run ../cmd/extract -gen -o debug_buildinfo.go debug/buildinfo $GOROOT/src/debug/buildinfo
//go:generate go run ../cmd/extract -gen -o debug_pe.go debug/pe $GOROOT/src/debug/pe
//go:generate go run ../cmd/extract -gen -o debug_plan9obj.go debug/plan9obj $GOROOT/src/debug/plan9obj
//go:generate go run ../cmd/extract -gen -o embed.go embed $GOROOT/src/embed
//go:generate go run ../cmd/extract -gen -o encoding.go encoding $GOROOT/src/encoding
//go:generate go run ../cmd/extract -gen -o encoding_ascii85.go encoding/ascii85 $GOROOT/src/encoding/ascii85
//go:generate go run ../cmd/extract -gen -o encoding_asn1.go encoding/asn1 $GOROOT/src/encoding/asn1
//go:generate go run ../cmd/extract -gen -o encoding_base32.go encoding/base32 $GOROOT/src/encoding/base32
//go:generate go run ../cmd/extract -gen -o encoding_base64.go encoding/base64 $GOROOT/src/encoding/base64
//go:generate go run ../cmd/extract -gen -o encoding_binary.go encoding/binary $GOROOT/src/encoding/binary
//go:generate go run ../cmd/extract -gen -o encoding_csv.go encoding/csv $GOROOT/src/encoding/csv
//go:generate go run ../cmd/extract -gen -o encoding_gob.go encoding/gob $GOROOT/src/encoding/gob
//go:generate go run ../cmd/extract -gen -o encoding_hex.go encoding/hex $GOROOT/src/encoding/hex
//go:generate go run ../cmd/extract -gen -o encoding_json.go encoding/json $GOROOT/src/encoding/json
//go:generate go run ../cmd/extract -gen -o encoding_pem.go encoding/pem $GOROOT/src/encoding/pem
//go:generate go run ../cmd/extract -gen -o encoding_xml.go encoding/xml $GOROOT/src/encoding/xml
//go:generate go run ../cmd/extract -gen -o errors.go errors $GOROOT/src/errors
//go:generate go run ../cmd/extract -gen -o expvar.go expvar $GOROOT/src/expvar
//go:generate go run ../cmd/extract -gen -o flag.go flag $GOROOT/src/flag
//go:generate go run ../cmd/extract -gen -o fmt.go fmt $GOROOT/src/fmt
//go:generate go run ../cmd/extract -gen -o go_ast.go go/ast $GOROOT/src/go/ast
//go:generate go run ../cmd/extract -gen -o go_build.go go/build $GOROOT/src/go/build
//go:generate go run ../cmd/extract -gen -o go_build_constraint.go go/build/constraint $GOROOT/src/go/build/constraint
//go:generate go run ../cmd/extract -gen -o go_constant.go go/constant $GOROOT/src/go/constant
//go:generate go run ../cmd/extract -gen -o go_doc.go go/doc $GOROOT/src/go/doc
//go:generate go run ../cmd/extract -gen -o go_doc_comment.go go/doc/comment $GOROOT/src/go/doc/comment
//go:generate go run ../cmd/extract -gen -o go_format.go go/format $GOROOT/src/go/format
//go:generate go run ../cmd/extract -gen -o go_parser.go go/parser $GOROOT/src/go/parser
//go:generate go run ../cmd/extract -gen -o go_printer.go go/printer $GOROOT/src/go/printer
//go:generate go run ../cmd/extract -gen -o go_scanner.go go/scanner $GOROOT/src/go/scanner
//go:generate go run ../cmd/extract -gen -o go_token.go go/token $GOROOT/src/go/token
//go:generate go run ../cmd/extract -gen -o go_types.go go/types $GOROOT/src/go/types
//go:generate go run ../cmd/extract -gen -o go_importer.go go/importer $GOROOT/src/go/importer
//go:generate go run ../cmd/extract -gen -o go_version.go go/version $GOROOT/src/go/version
//go:generate go run ../cmd/extract -gen -o hash.go hash $GOROOT/src/hash
//go:generate go run ../cmd/extract -gen -o hash_adler32.go hash/adler32 $GOROOT/src/hash/adler32
//go:generate go run ../cmd/extract -gen -o hash_crc32.go hash/crc32 $GOROOT/src/hash/crc32
//go:generate go run ../cmd/extract -gen -o hash_crc64.go hash/crc64 $GOROOT/src/hash/crc64
//go:generate go run ../cmd/extract -gen -o hash_fnv.go hash/fnv $GOROOT/src/hash/fnv
//go:generate go run ../cmd/extract -gen -o hash_maphash.go hash/maphash $GOROOT/src/hash/maphash
//go:generate go run ../cmd/extract -gen -o html.go html $GOROOT/src/html
//go:generate go run ../cmd/extract -gen -o html_template.go html/template $GOROOT/src/html/template
//go:generate go run ../cmd/extract -gen -o image.go image $GOROOT/src/image
//go:generate go run ../cmd/extract -gen -o image_color.go image/color $GOROOT/src/image/color
//go:generate go run ../cmd/extract -gen -o image_color_palette.go image/color/palette $GOROOT/src/image/color/palette
//go:generate go run ../cmd/extract -gen -o image_draw.go image/draw $GOROOT/src/image/draw
//go:generate go run ../cmd/extract -gen -o image_gif.go image/gif $GOROOT/src/image/gif
//go:generate go run ../cmd/extract -gen -o image_jpeg.go image/jpeg $GOROOT/src/image/jpeg
//go:generate go run ../cmd/extract -gen -o image_png.go image/png $GOROOT/src/image/png
//go:generate go run ../cmd/extract -gen -o index_suffixarray.go index/suffixarray $GOROOT/src/index/suffixarray
//go:generate go run ../cmd/extract -gen -o io.go io $GOROOT/src/io
//go:generate go run ../cmd/extract -gen -o io_fs.go io/fs $GOROOT/src/io/fs
//go:generate go run ../cmd/extract -gen -o io_ioutil.go io/ioutil $GOROOT/src/io/ioutil
//go:generate go run ../cmd/extract -gen -o log.go log $GOROOT/src/log
//go:generate go run ../cmd/extract -gen -o log_slog.go log/slog $GOROOT/src/log/slog
//go:generate go run ../cmd/extract -gen -o log_syslog.go log/syslog $GOROOT/src/log/syslog
//go:generate go run ../cmd/extract -gen -o math.go math $GOROOT/src/math
//go:generate go run ../cmd/extract -gen -o math_big.go math/big $GOROOT/src/math/big
//go:generate go run ../cmd/extract -gen -o math_bits.go math/bits $GOROOT/src/math/bits
//go:generate go run ../cmd/extract -gen -o math_cmplx.go math/cmplx $GOROOT/src/math/cmplx
//go:generate go run ../cmd/extract -gen -o math_rand.go math/rand $GOROOT/src/math/rand
//go:generate go run ../cmd/extract -gen -o math_rand_v2.go math/rand/v2 $GOROOT/src/math/rand/v2
//go:generate go run ../cmd/extract -gen -o mime.go mime $GOROOT/src/mime
//go:generate go run ../cmd/extract -gen -o mime_multipart.go mime/multipart $GOROOT/src/mime/multipart
//go:generate go run ../cmd/extract -gen -o mime_quotedprintable.go mime/quotedprintable $GOROOT/src/mime/quotedprintable
//go:generate go run ../cmd/extract -gen -o net.go net $GOROOT/src/net
//go:generate go run ../cmd/extract -gen -o net_http.go net/http $GOROOT/src/net/http
//go:generate go run ../cmd/extract -gen -o net_http_cgi.go net/http/cgi $GOROOT/src/net/http/cgi
//go:generate go run ../cmd/extract -gen -o net_http_cookiejar.go net/http/cookiejar $GOROOT/src/net/http/cookiejar
//go:generate go run ../cmd/extract -gen -o net_http_fcgi.go net/http/fcgi $GOROOT/src/net/http/fcgi
//go:generate go run ../cmd/extract -gen -o net_http_httptest.go net/http/httptest $GOROOT/src/net/http/httptest
//go:generate go run ../cmd/extract -gen -o net_http_httptrace.go net/http/httptrace $GOROOT/src/net/http/httptrace
//go:generate go run ../cmd/extract -gen -o net_http_httputil.go net/http/httputil $GOROOT/src/net/http/httputil
//go:generate go run ../cmd/extract -gen -o net_http_pprof.go net/http/pprof $GOROOT/src/net/http/pprof
//go:generate go run ../cmd/extract -gen -o net_mail.go net/mail $GOROOT/src/net/mail
//go:generate go run ../cmd/extract -gen -o net_netip.go net/netip $GOROOT/src/net/netip
//go:generate go run ../cmd/extract -gen -o net_rpc.go net/rpc $GOROOT/src/net/rpc
//go:generate go run ../cmd/extract -gen -o net_rpc_jsonrpc.go net/rpc/jsonrpc $GOROOT/src/net/rpc/jsonrpc
//go:generate go run ../cmd/extract -gen -o net_smtp.go net/smtp $GOROOT/src/net/smtp
//go:generate go run ../cmd/extract -gen -o net_textproto.go net/textproto $GOROOT/src/net/textproto
//go:generate go run ../cmd/extract -gen -o net_url.go net/url $GOROOT/src/net/url
//go:generate go run ../cmd/extract -gen -o os.go os $GOROOT/src/os
//go:generate go run ../cmd/extract -gen -o os_exec.go os/exec $GOROOT/src/os/exec
//go:generate go run ../cmd/extract -gen -o os_signal.go os/signal $GOROOT/src/os/signal
//go:generate go run ../cmd/extract -gen -o os_user.go os/user $GOROOT/src/os/user
//go:generate go run ../cmd/extract -gen -o path.go path $GOROOT/src/path
//go:generate go run ../cmd/extract -gen -o path_filepath.go path/filepath $GOROOT/src/path/filepath
//go:generate go run ../cmd/extract -gen -o reflect.go reflect $GOROOT/src/reflect
//go:generate go run ../cmd/extract -gen -o regexp.go regexp $GOROOT/src/regexp
//go:generate go run ../cmd/extract -gen -o regexp_syntax.go regexp/syntax $GOROOT/src/regexp/syntax
//go:generate go run ../cmd/extract -gen -o runtime.go runtime $GOROOT/src/runtime
//go:generate go run ../cmd/extract -gen -o runtime_cgo.go runtime/cgo $GOROOT/src/runtime/cgo
//go:generate go run ../cmd/extract -gen -o runtime_coverage.go runtime/coverage $GOROOT/src/runtime/coverage
//go:generate go run ../cmd/extract -gen -o runtime_debug.go runtime/debug $GOROOT/src/runtime/debug
//go:generate go run ../cmd/extract -gen -o runtime_metrics.go runtime/metrics $GOROOT/src/runtime/metrics
//go:generate go run ../cmd/extract -gen -o runtime_pprof.go runtime/pprof $GOROOT/src/runtime/pprof
//go:generate go run ../cmd/extract -gen -o runtime_trace.go runtime/trace $GOROOT/src/runtime/trace
//go:generate go run ../cmd/extract -gen -o sort.go sort $GOROOT/src/sort
//go:generate go run ../cmd/extract -gen -o strconv.go strconv $GOROOT/src/strconv
//go:generate go run ../cmd/extract -gen -o strings.go strings $GOROOT/src/strings
//go:generate go run ../cmd/extract -gen -o structs.go structs $GOROOT/src/structs
//go:generate go run ../cmd/extract -gen -o sync.go sync $GOROOT/src/sync
//go:generate go run ../cmd/extract -gen -o sync_atomic.go sync/atomic $GOROOT/src/sync/atomic
//go:generate go run ../cmd/extract -gen -o testing.go testing $GOROOT/src/testing
//go:generate go run ../cmd/extract -gen -o testing_fstest.go testing/fstest $GOROOT/src/testing/fstest
//go:generate go run ../cmd/extract -gen -o testing_iotest.go testing/iotest $GOROOT/src/testing/iotest
//go:generate go run ../cmd/extract -gen -o testing_quick.go testing/quick $GOROOT/src/testing/quick
//go:generate go run ../cmd/extract -gen -o testing_synctest.go testing/synctest $GOROOT/src/testing/synctest
//go:generate go run ../cmd/extract -gen -o text_scanner.go text/scanner $GOROOT/src/text/scanner
//go:generate go run ../cmd/extract -gen -o text_tabwriter.go text/tabwriter $GOROOT/src/text/tabwriter
//go:generate go run ../cmd/extract -gen -o text_template.go text/template $GOROOT/src/text/template
//go:generate go run ../cmd/extract -gen -o text_template_parse.go text/template/parse $GOROOT/src/text/template/parse
//go:generate go run ../cmd/extract -gen -o time.go time $GOROOT/src/time
//go:generate go run ../cmd/extract -gen -o unicode.go unicode $GOROOT/src/unicode
//go:generate go run ../cmd/extract -gen -o unicode_utf16.go unicode/utf16 $GOROOT/src/unicode/utf16
//go:generate go run ../cmd/extract -gen -o unicode_utf8.go unicode/utf8 $GOROOT/src/unicode/utf8
