// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/build"
	"reflect"
)

func init() {
	Values["go/build"] = map[string]reflect.Value{
		"AllowBinary": reflect.ValueOf(build.AllowBinary),
		"ArchChar": reflect.ValueOf(build.ArchChar),
		"FindOnly": reflect.ValueOf(build.FindOnly),
		"IgnoreVendor": reflect.ValueOf(build.IgnoreVendor),
		"Import": reflect.ValueOf(build.Import),
		"ImportComment": reflect.ValueOf(build.ImportComment),
		"ImportDir": reflect.ValueOf(build.ImportDir),
		"IsLocalImport": reflect.ValueOf(build.IsLocalImport),
		"Default": reflect.ValueOf(&build.Default),
		"ToolDir": reflect.ValueOf(&build.ToolDir),
		"Context": reflect.ValueOf((*build.Context)(nil)),
		"Directive": reflect.ValueOf((*build.Directive)(nil)),
		"ImportMode": reflect.ValueOf((*build.ImportMode)(nil)),
		"MultiplePackageError": reflect.ValueOf((*build.MultiplePackageError)(nil)),
		"NoGoError": reflect.ValueOf((*build.NoGoError)(nil)),
		"Package": reflect.ValueOf((*build.Package)(nil)),
	}
}
