// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/doc"
	"reflect"
)

func init() {
	Values["go/doc"] = map[string]reflect.Value{
		"AllDecls": reflect.ValueOf(doc.AllDecls),
		"AllMethods": reflect.ValueOf(doc.AllMethods),
		"Examples": reflect.ValueOf(doc.Examples),
		"IsPredeclared": reflect.ValueOf(doc.IsPredeclared),
		"New": reflect.ValueOf(doc.New),
		"NewFromFiles": reflect.ValueOf(doc.NewFromFiles),
		"PreserveAST": reflect.ValueOf(doc.PreserveAST),
		"Synopsis": reflect.ValueOf(doc.Synopsis),
		"ToHTML": reflect.ValueOf(doc.ToHTML),
		"ToText": reflect.ValueOf(doc.ToText),
		"IllegalPrefixes": reflect.ValueOf(&doc.IllegalPrefixes),
		"Example": reflect.ValueOf((*doc.Example)(nil)),
		"Filter": reflect.ValueOf((*doc.Filter)(nil)),
		"Func": reflect.ValueOf((*doc.Func)(nil)),
		"Mode": reflect.ValueOf((*doc.Mode)(nil)),
		"Note": reflect.ValueOf((*doc.Note)(nil)),
		"Package": reflect.ValueOf((*doc.Package)(nil)),
		"Type": reflect.ValueOf((*doc.Type)(nil)),
		"Value": reflect.ValueOf((*doc.Value)(nil)),
	}
}
