// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/doc/comment"
	"reflect"
)

func init() {
	Values["go/doc/comment"] = map[string]reflect.Value{
		"DefaultLookupPackage": reflect.ValueOf(comment.DefaultLookupPackage),
		"Block": reflect.ValueOf((*comment.Block)(nil)),
		"Code": reflect.ValueOf((*comment.Code)(nil)),
		"Doc": reflect.ValueOf((*comment.Doc)(nil)),
		"DocLink": reflect.ValueOf((*comment.DocLink)(nil)),
		"Heading": reflect.ValueOf((*comment.Heading)(nil)),
		"Italic": reflect.ValueOf((*comment.Italic)(nil)),
		"Link": reflect.ValueOf((*comment.Link)(nil)),
		"LinkDef": reflect.ValueOf((*comment.LinkDef)(nil)),
		"List": reflect.ValueOf((*comment.List)(nil)),
		"ListItem": reflect.ValueOf((*comment.ListItem)(nil)),
		"Paragraph": reflect.ValueOf((*comment.Paragraph)(nil)),
		"Parser": reflect.ValueOf((*comment.Parser)(nil)),
		"Plain": reflect.ValueOf((*comment.Plain)(nil)),
		"Printer": reflect.ValueOf((*comment.Printer)(nil)),
		"Text": reflect.ValueOf((*comment.Text)(nil)),
	}
}
