// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/format"
	"reflect"
)

func init() {
	Values["go/format"] = map[string]reflect.Value{
		"Node": reflect.ValueOf(format.Node),
		"Source": reflect.ValueOf(format.Source),
	}
}
