// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/importer"
	"reflect"
)

func init() {
	Values["go/importer"] = map[string]reflect.Value{
		"Default": reflect.ValueOf(importer.Default),
		"For": reflect.ValueOf(importer.For),
		"ForCompiler": reflect.ValueOf(importer.ForCompiler),
		"Lookup": reflect.ValueOf((*importer.Lookup)(nil)),
	}
}
