// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/printer"
	"reflect"
)

func init() {
	Values["go/printer"] = map[string]reflect.Value{
		"RawFormat": reflect.ValueOf(printer.RawFormat),
		"SourcePos": reflect.ValueOf(printer.SourcePos),
		"TabIndent": reflect.ValueOf(printer.TabIndent),
		"UseSpaces": reflect.ValueOf(printer.UseSpaces),
		"CommentedNode": reflect.ValueOf((*printer.CommentedNode)(nil)),
		"Config": reflect.ValueOf((*printer.Config)(nil)),
		"Mode": reflect.ValueOf((*printer.Mode)(nil)),
	}
}
