// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"go/version"
	"reflect"
)

func init() {
	Values["go/version"] = map[string]reflect.Value{
		"Compare": reflect.ValueOf(version.Compare),
		"IsValid": reflect.ValueOf(version.IsValid),
		"Lang": reflect.ValueOf(version.Lang),
	}
}
