// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"hash/maphash"
	"reflect"
)

func init() {
	Values["hash/maphash"] = map[string]reflect.Value{
		"Bytes": reflect.ValueOf(maphash.Bytes),
		"MakeSeed": reflect.ValueOf(maphash.MakeSeed),
		"String": reflect.ValueOf(maphash.String),
		"Hash": reflect.ValueOf((*maphash.Hash)(nil)),
		"Seed": reflect.ValueOf((*maphash.Seed)(nil)),
	}
}
