// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"hash/adler32"
	"reflect"
)

func init() {
	Values["hash/adler32"] = map[string]reflect.Value{
		"Checksum": reflect.ValueOf(adler32.Checksum),
		"New": reflect.ValueOf(adler32.New),
		"Size": reflect.ValueOf(adler32.Size),
	}
}
