// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"hash/crc64"
	"reflect"
)

func init() {
	Values["hash/crc64"] = map[string]reflect.Value{
		"Checksum": reflect.ValueOf(crc64.Checksum),
		"ECMA": reflect.ValueOf(uint64(crc64.ECMA)),
		"ISO": reflect.ValueOf(uint64(crc64.ISO)),
		"MakeTable": reflect.ValueOf(crc64.MakeTable),
		"New": reflect.ValueOf(crc64.New),
		"Size": reflect.ValueOf(crc64.Size),
		"Update": reflect.ValueOf(crc64.Update),
		"Table": reflect.ValueOf((*crc64.Table)(nil)),
	}
}
