// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"hash/crc32"
	"reflect"
)

func init() {
	Values["hash/crc32"] = map[string]reflect.Value{
		"Castagnoli": reflect.ValueOf(crc32.Castagnoli),
		"Checksum": reflect.ValueOf(crc32.Checksum),
		"ChecksumIEEE": reflect.ValueOf(crc32.ChecksumIEEE),
		"IEEE": reflect.ValueOf(crc32.IEEE),
		"Koopman": reflect.ValueOf(crc32.Koopman),
		"MakeTable": reflect.ValueOf(crc32.MakeTable),
		"New": reflect.ValueOf(crc32.New),
		"NewIEEE": reflect.ValueOf(crc32.NewIEEE),
		"Size": reflect.ValueOf(crc32.Size),
		"Update": reflect.ValueOf(crc32.Update),
		"IEEETable": reflect.ValueOf(&crc32.IEEETable),
		"Table": reflect.ValueOf((*crc32.Table)(nil)),
	}
}
