// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"html/template"
	"reflect"
)

func init() {
	Values["html/template"] = map[string]reflect.Value{
		"ErrAmbigContext": reflect.ValueOf(template.ErrAmbigContext),
		"ErrBadHTML": reflect.ValueOf(template.ErrBadHTML),
		"ErrBranchEnd": reflect.ValueOf(template.ErrBranchEnd),
		"ErrEndContext": reflect.ValueOf(template.ErrEndContext),
		"ErrJSTemplate": reflect.ValueOf(template.ErrJSTemplate),
		"ErrNoSuchTemplate": reflect.ValueOf(template.ErrNoSuchTemplate),
		"ErrOutputContext": reflect.ValueOf(template.ErrOutputContext),
		"ErrPartialCharset": reflect.ValueOf(template.ErrPartialCharset),
		"ErrPartialEscape": reflect.ValueOf(template.ErrPartialEscape),
		"ErrPredefinedEscaper": reflect.ValueOf(template.ErrPredefinedEscaper),
		"ErrRangeLoopReentry": reflect.ValueOf(template.ErrRangeLoopReentry),
		"ErrSlashAmbig": reflect.ValueOf(template.ErrSlashAmbig),
		"HTMLEscape": reflect.ValueOf(template.HTMLEscape),
		"HTMLEscapeString": reflect.ValueOf(template.HTMLEscapeString),
		"HTMLEscaper": reflect.ValueOf(template.HTMLEscaper),
		"IsTrue": reflect.ValueOf(template.IsTrue),
		"JSEscape": reflect.ValueOf(template.JSEscape),
		"JSEscapeString": reflect.ValueOf(template.JSEscapeString),
		"JSEscaper": reflect.ValueOf(template.JSEscaper),
		"Must": reflect.ValueOf(template.Must),
		"New": reflect.ValueOf(template.New),
		"OK": reflect.ValueOf(template.OK),
		"ParseFiles": reflect.ValueOf(template.ParseFiles),
		"ParseGlob": reflect.ValueOf(template.ParseGlob),
		"URLQueryEscaper": reflect.ValueOf(template.URLQueryEscaper),
		"Error": reflect.ValueOf((*template.Error)(nil)),
		"ErrorCode": reflect.ValueOf((*template.ErrorCode)(nil)),
		"FuncMap": reflect.ValueOf((*template.FuncMap)(nil)),
		"Template": reflect.ValueOf((*template.Template)(nil)),
	}
}
