// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"html"
	"reflect"
)

func init() {
	Values["html"] = map[string]reflect.Value{
		"EscapeString": reflect.ValueOf(html.EscapeString),
		"UnescapeString": reflect.ValueOf(html.UnescapeString),
	}
}
