// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"image/color/palette"
	"reflect"
)

func init() {
	Values["image/color/palette"] = map[string]reflect.Value{
		"Plan9": reflect.ValueOf(&palette.Plan9),
		"WebSafe": reflect.ValueOf(&palette.WebSafe),
	}
}
