// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"image/color"
	"reflect"
)

func init() {
	Values["image/color"] = map[string]reflect.Value{
		"CMYKToRGB": reflect.ValueOf(color.CMYKToRGB),
		"ModelFunc": reflect.ValueOf(color.ModelFunc),
		"RGBToCMYK": reflect.ValueOf(color.RGBToCMYK),
		"RGBToYCbCr": reflect.ValueOf(color.RGBToYCbCr),
		"YCbCrToRGB": reflect.ValueOf(color.YCbCrToRGB),
		"Alpha16Model": reflect.ValueOf(&color.Alpha16Model),
		"AlphaModel": reflect.ValueOf(&color.AlphaModel),
		"Black": reflect.ValueOf(&color.Black),
		"CMYKModel": reflect.ValueOf(&color.CMYKModel),
		"Gray16Model": reflect.ValueOf(&color.Gray16Model),
		"GrayModel": reflect.ValueOf(&color.GrayModel),
		"NRGBA64Model": reflect.ValueOf(&color.NRGBA64Model),
		"NRGBAModel": reflect.ValueOf(&color.NRGBAModel),
		"NYCbCrAModel": reflect.ValueOf(&color.NYCbCrAModel),
		"Opaque": reflect.ValueOf(&color.Opaque),
		"RGBA64Model": reflect.ValueOf(&color.RGBA64Model),
		"RGBAModel": reflect.ValueOf(&color.RGBAModel),
		"Transparent": reflect.ValueOf(&color.Transparent),
		"White": reflect.ValueOf(&color.White),
		"YCbCrModel": reflect.ValueOf(&color.YCbCrModel),
		"Alpha": reflect.ValueOf((*color.Alpha)(nil)),
		"Alpha16": reflect.ValueOf((*color.Alpha16)(nil)),
		"CMYK": reflect.ValueOf((*color.CMYK)(nil)),
		"Color": reflect.ValueOf((*color.Color)(nil)),
		"Gray": reflect.ValueOf((*color.Gray)(nil)),
		"Gray16": reflect.ValueOf((*color.Gray16)(nil)),
		"Model": reflect.ValueOf((*color.Model)(nil)),
		"NRGBA": reflect.ValueOf((*color.NRGBA)(nil)),
		"NRGBA64": reflect.ValueOf((*color.NRGBA64)(nil)),
		"NYCbCrA": reflect.ValueOf((*color.NYCbCrA)(nil)),
		"Palette": reflect.ValueOf((*color.Palette)(nil)),
		"RGBA": reflect.ValueOf((*color.RGBA)(nil)),
		"RGBA64": reflect.ValueOf((*color.RGBA64)(nil)),
		"YCbCr": reflect.ValueOf((*color.YCbCr)(nil)),
	}
}
