// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"image/gif"
	"reflect"
)

func init() {
	Values["image/gif"] = map[string]reflect.Value{
		"DisposalBackground": reflect.ValueOf(gif.DisposalBackground),
		"DisposalNone": reflect.ValueOf(gif.DisposalNone),
		"DisposalPrevious": reflect.ValueOf(gif.DisposalPrevious),
		"GIF": reflect.ValueOf((*gif.GIF)(nil)),
		"Options": reflect.ValueOf((*gif.Options)(nil)),
	}
}
