// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"image/draw"
	"reflect"
)

func init() {
	Values["image/draw"] = map[string]reflect.Value{
		"Over": reflect.ValueOf(draw.Over),
		"Src": reflect.ValueOf(draw.Src),
		"FloydSteinberg": reflect.ValueOf(&draw.FloydSteinberg),
		"Drawer": reflect.ValueOf((*draw.Drawer)(nil)),
		"Op": reflect.ValueOf((*draw.Op)(nil)),
		"Quantizer": reflect.ValueOf((*draw.Quantizer)(nil)),
	}
}
