// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"index/suffixarray"
	"reflect"
)

func init() {
	Values["index/suffixarray"] = map[string]reflect.Value{
		"New": reflect.ValueOf(suffixarray.New),
		"Index": reflect.ValueOf((*suffixarray.Index)(nil)),
	}
}
