// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"io"
	"reflect"
)

func init() {
	Values["io"] = map[string]reflect.Value{
		"Copy": reflect.ValueOf(io.Copy),
		"CopyBuffer": reflect.ValueOf(io.CopyBuffer),
		"CopyN": reflect.ValueOf(io.CopyN),
		"LimitReader": reflect.ValueOf(io.LimitReader),
		"MultiReader": reflect.ValueOf(io.MultiReader),
		"MultiWriter": reflect.ValueOf(io.MultiWriter),
		"NewOffsetWriter": reflect.ValueOf(io.NewOffsetWriter),
		"NewSectionReader": reflect.ValueOf(io.NewSectionReader),
		"NopCloser": reflect.ValueOf(io.NopCloser),
		"Pipe": reflect.ValueOf(io.Pipe),
		"ReadAll": reflect.ValueOf(io.ReadAll),
		"ReadAtLeast": reflect.ValueOf(io.ReadAtLeast),
		"ReadFull": reflect.ValueOf(io.ReadFull),
		"SeekCurrent": reflect.ValueOf(io.SeekCurrent),
		"SeekEnd": reflect.ValueOf(io.SeekEnd),
		"SeekStart": reflect.ValueOf(io.SeekStart),
		"TeeReader": reflect.ValueOf(io.TeeReader),
		"WriteString": reflect.ValueOf(io.WriteString),
		"Discard": reflect.ValueOf(&io.Discard),
		"EOF": reflect.ValueOf(&io.EOF),
		"ErrClosedPipe": reflect.ValueOf(&io.ErrClosedPipe),
		"ErrNoProgress": reflect.ValueOf(&io.ErrNoProgress),
		"ErrShortBuffer": reflect.ValueOf(&io.ErrShortBuffer),
		"ErrShortWrite": reflect.ValueOf(&io.ErrShortWrite),
		"ErrUnexpectedEOF": reflect.ValueOf(&io.ErrUnexpectedEOF),
		"ByteReader": reflect.ValueOf((*io.ByteReader)(nil)),
		"ByteScanner": reflect.ValueOf((*io.ByteScanner)(nil)),
		"ByteWriter": reflect.ValueOf((*io.ByteWriter)(nil)),
		"Closer": reflect.ValueOf((*io.Closer)(nil)),
		"LimitedReader": reflect.ValueOf((*io.LimitedReader)(nil)),
		"OffsetWriter": reflect.ValueOf((*io.OffsetWriter)(nil)),
		"PipeReader": reflect.ValueOf((*io.PipeReader)(nil)),
		"PipeWriter": reflect.ValueOf((*io.PipeWriter)(nil)),
		"ReadCloser": reflect.ValueOf((*io.ReadCloser)(nil)),
		"ReadSeekCloser": reflect.ValueOf((*io.ReadSeekCloser)(nil)),
		"ReadSeeker": reflect.ValueOf((*io.ReadSeeker)(nil)),
		"ReadWriteCloser": reflect.ValueOf((*io.ReadWriteCloser)(nil)),
		"ReadWriteSeeker": reflect.ValueOf((*io.ReadWriteSeeker)(nil)),
		"ReadWriter": reflect.ValueOf((*io.ReadWriter)(nil)),
		"Reader": reflect.ValueOf((*io.Reader)(nil)),
		"ReaderAt": reflect.ValueOf((*io.ReaderAt)(nil)),
		"ReaderFrom": reflect.ValueOf((*io.ReaderFrom)(nil)),
		"RuneReader": reflect.ValueOf((*io.RuneReader)(nil)),
		"RuneScanner": reflect.ValueOf((*io.RuneScanner)(nil)),
		"SectionReader": reflect.ValueOf((*io.SectionReader)(nil)),
		"Seeker": reflect.ValueOf((*io.Seeker)(nil)),
		"StringWriter": reflect.ValueOf((*io.StringWriter)(nil)),
		"WriteCloser": reflect.ValueOf((*io.WriteCloser)(nil)),
		"WriteSeeker": reflect.ValueOf((*io.WriteSeeker)(nil)),
		"Writer": reflect.ValueOf((*io.Writer)(nil)),
		"WriterAt": reflect.ValueOf((*io.WriterAt)(nil)),
		"WriterTo": reflect.ValueOf((*io.WriterTo)(nil)),
	}
}
