// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"io/fs"
	"reflect"
)

func init() {
	Values["io/fs"] = map[string]reflect.Value{
		"FileInfoToDirEntry": reflect.ValueOf(fs.FileInfoToDirEntry),
		"FormatDirEntry": reflect.ValueOf(fs.FormatDirEntry),
		"FormatFileInfo": reflect.ValueOf(fs.FormatFileInfo),
		"Glob": reflect.ValueOf(fs.Glob),
		"Lstat": reflect.ValueOf(fs.Lstat),
		"ModeAppend": reflect.ValueOf(fs.ModeAppend),
		"ModeCharDevice": reflect.ValueOf(fs.ModeCharDevice),
		"ModeDevice": reflect.ValueOf(fs.ModeDevice),
		"ModeDir": reflect.ValueOf(fs.ModeDir),
		"ModeExclusive": reflect.ValueOf(fs.ModeExclusive),
		"ModeIrregular": reflect.ValueOf(fs.ModeIrregular),
		"ModeNamedPipe": reflect.ValueOf(fs.ModeNamedPipe),
		"ModePerm": reflect.ValueOf(fs.ModePerm),
		"ModeSetgid": reflect.ValueOf(fs.ModeSetgid),
		"ModeSetuid": reflect.ValueOf(fs.ModeSetuid),
		"ModeSocket": reflect.ValueOf(fs.ModeSocket),
		"ModeSticky": reflect.ValueOf(fs.ModeSticky),
		"ModeSymlink": reflect.ValueOf(fs.ModeSymlink),
		"ModeTemporary": reflect.ValueOf(fs.ModeTemporary),
		"ModeType": reflect.ValueOf(fs.ModeType),
		"ReadDir": reflect.ValueOf(fs.ReadDir),
		"ReadFile": reflect.ValueOf(fs.ReadFile),
		"ReadLink": reflect.ValueOf(fs.ReadLink),
		"Stat": reflect.ValueOf(fs.Stat),
		"Sub": reflect.ValueOf(fs.Sub),
		"ValidPath": reflect.ValueOf(fs.ValidPath),
		"ErrClosed": reflect.ValueOf(&fs.ErrClosed),
		"ErrExist": reflect.ValueOf(&fs.ErrExist),
		"ErrInvalid": reflect.ValueOf(&fs.ErrInvalid),
		"ErrNotExist": reflect.ValueOf(&fs.ErrNotExist),
		"ErrPermission": reflect.ValueOf(&fs.ErrPermission),
		"SkipAll": reflect.ValueOf(&fs.SkipAll),
		"SkipDir": reflect.ValueOf(&fs.SkipDir),
		"DirEntry": reflect.ValueOf((*fs.DirEntry)(nil)),
		"FS": reflect.ValueOf((*fs.FS)(nil)),
		"File": reflect.ValueOf((*fs.File)(nil)),
		"FileInfo": reflect.ValueOf((*fs.FileInfo)(nil)),
		"FileMode": reflect.ValueOf((*fs.FileMode)(nil)),
		"GlobFS": reflect.ValueOf((*fs.GlobFS)(nil)),
		"PathError": reflect.ValueOf((*fs.PathError)(nil)),
		"ReadDirFS": reflect.ValueOf((*fs.ReadDirFS)(nil)),
		"ReadDirFile": reflect.ValueOf((*fs.ReadDirFile)(nil)),
		"ReadFileFS": reflect.ValueOf((*fs.ReadFileFS)(nil)),
		"ReadLinkFS": reflect.ValueOf((*fs.ReadLinkFS)(nil)),
		"StatFS": reflect.ValueOf((*fs.StatFS)(nil)),
		"SubFS": reflect.ValueOf((*fs.SubFS)(nil)),
	}
}
