// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"io/ioutil"
	"reflect"
)

func init() {
	Values["io/ioutil"] = map[string]reflect.Value{
		"ReadFile": reflect.ValueOf(ioutil.ReadFile),
		"TempDir": reflect.ValueOf(ioutil.TempDir),
		"Discard": reflect.ValueOf(&ioutil.Discard),
	}
}
