// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"math/rand/v2"
	"reflect"
)

func init() {
	Values["math/rand/v2"] = map[string]reflect.Value{
		"ExpFloat64": reflect.ValueOf(rand.ExpFloat64),
		"Float32": reflect.ValueOf(rand.Float32),
		"Float64": reflect.ValueOf(rand.Float64),
		"Int": reflect.ValueOf(rand.Int),
		"Int32": reflect.ValueOf(rand.Int32),
		"Int32N": reflect.ValueOf(rand.Int32N),
		"Int64": reflect.ValueOf(rand.Int64),
		"Int64N": reflect.ValueOf(rand.Int64N),
		"IntN": reflect.ValueOf(rand.IntN),
		"New": reflect.ValueOf(rand.New),
		"NewChaCha8": reflect.ValueOf(rand.NewChaCha8),
		"NewPCG": reflect.ValueOf(rand.NewPCG),
		"NewZipf": reflect.ValueOf(rand.NewZipf),
		"NormFloat64": reflect.ValueOf(rand.NormFloat64),
		"Perm": reflect.ValueOf(rand.Perm),
		"Shuffle": reflect.ValueOf(rand.Shuffle),
		"Uint": reflect.ValueOf(rand.Uint),
		"Uint32": reflect.ValueOf(rand.Uint32),
		"Uint32N": reflect.ValueOf(rand.Uint32N),
		"Uint64": reflect.ValueOf(rand.Uint64),
		"Uint64N": reflect.ValueOf(rand.Uint64N),
		"UintN": reflect.ValueOf(rand.UintN),
		"ChaCha8": reflect.ValueOf((*rand.ChaCha8)(nil)),
		"PCG": reflect.ValueOf((*rand.PCG)(nil)),
		"Rand": reflect.ValueOf((*rand.Rand)(nil)),
		"Source": reflect.ValueOf((*rand.Source)(nil)),
		"Zipf": reflect.ValueOf((*rand.Zipf)(nil)),
	}
}
