// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"mime/multipart"
	"reflect"
)

func init() {
	Values["mime/multipart"] = map[string]reflect.Value{
		"FileContentDisposition": reflect.ValueOf(multipart.FileContentDisposition),
		"NewReader": reflect.ValueOf(multipart.NewReader),
		"NewWriter": reflect.ValueOf(multipart.NewWriter),
		"ErrMessageTooLarge": reflect.ValueOf(&multipart.ErrMessageTooLarge),
		"FileHeader": reflect.ValueOf((*multipart.FileHeader)(nil)),
		"Form": reflect.ValueOf((*multipart.Form)(nil)),
		"Part": reflect.ValueOf((*multipart.Part)(nil)),
		"Reader": reflect.ValueOf((*multipart.Reader)(nil)),
		"Writer": reflect.ValueOf((*multipart.Writer)(nil)),
	}
}
