// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"mime"
	"reflect"
)

func init() {
	Values["mime"] = map[string]reflect.Value{
		"AddExtensionType": reflect.ValueOf(mime.AddExtensionType),
		"BEncoding": reflect.ValueOf(mime.BEncoding),
		"ExtensionsByType": reflect.ValueOf(mime.ExtensionsByType),
		"FormatMediaType": reflect.ValueOf(mime.FormatMediaType),
		"ParseMediaType": reflect.ValueOf(mime.ParseMediaType),
		"QEncoding": reflect.ValueOf(mime.QEncoding),
		"TypeByExtension": reflect.ValueOf(mime.TypeByExtension),
		"ErrInvalidMediaParameter": reflect.ValueOf(&mime.ErrInvalidMediaParameter),
		"WordDecoder": reflect.ValueOf((*mime.WordDecoder)(nil)),
		"WordEncoder": reflect.ValueOf((*mime.WordEncoder)(nil)),
	}
}
