// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"mime/quotedprintable"
	"reflect"
)

func init() {
	Values["mime/quotedprintable"] = map[string]reflect.Value{
		"NewReader": reflect.ValueOf(quotedprintable.NewReader),
		"NewWriter": reflect.ValueOf(quotedprintable.NewWriter),
		"Reader": reflect.ValueOf((*quotedprintable.Reader)(nil)),
		"Writer": reflect.ValueOf((*quotedprintable.Writer)(nil)),
	}
}
