// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/pprof"
	"reflect"
)

func init() {
	Values["net/http/pprof"] = map[string]reflect.Value{
		"Cmdline": reflect.ValueOf(pprof.Cmdline),
		"Handler": reflect.ValueOf(pprof.Handler),
		"Index": reflect.ValueOf(pprof.Index),
		"Profile": reflect.ValueOf(pprof.Profile),
		"Symbol": reflect.ValueOf(pprof.Symbol),
		"Trace": reflect.ValueOf(pprof.Trace),
	}
}
