// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/httptrace"
	"reflect"
)

func init() {
	Values["net/http/httptrace"] = map[string]reflect.Value{
		"ClientTrace": reflect.ValueOf((*httptrace.ClientTrace)(nil)),
		"DNSDoneInfo": reflect.ValueOf((*httptrace.DNSDoneInfo)(nil)),
		"DNSStartInfo": reflect.ValueOf((*httptrace.DNSStartInfo)(nil)),
		"GotConnInfo": reflect.ValueOf((*httptrace.GotConnInfo)(nil)),
		"WroteRequestInfo": reflect.ValueOf((*httptrace.WroteRequestInfo)(nil)),
	}
}
