// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/cgi"
	"reflect"
)

func init() {
	Values["net/http/cgi"] = map[string]reflect.Value{
		"Request": reflect.ValueOf(cgi.Request),
		"RequestFromMap": reflect.ValueOf(cgi.RequestFromMap),
		"Serve": reflect.ValueOf(cgi.Serve),
		"Handler": reflect.ValueOf((*cgi.Handler)(nil)),
	}
}
