// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/rpc/jsonrpc"
	"reflect"
)

func init() {
	Values["net/rpc/jsonrpc"] = map[string]reflect.Value{
		"Dial": reflect.ValueOf(jsonrpc.Dial),
		"NewClient": reflect.ValueOf(jsonrpc.NewClient),
		"NewClientCodec": reflect.ValueOf(jsonrpc.NewClientCodec),
		"NewServerCodec": reflect.ValueOf(jsonrpc.NewServerCodec),
		"ServeConn": reflect.ValueOf(jsonrpc.ServeConn),
	}
}
