// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/cgi"
	"reflect"
)

func init() {
	Values["net/http/cgi"] = map[string]reflect.Value{
		"Handler": reflect.ValueOf((*cgi.Handler)(nil)),
	}
}
