// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/httptest"
	"reflect"
)

func init() {
	Values["net/http/httptest"] = map[string]reflect.Value{
		"DefaultRemoteAddr": reflect.ValueOf(httptest.DefaultRemoteAddr),
		"NewRecorder": reflect.ValueOf(httptest.NewRecorder),
		"ResponseRecorder": reflect.ValueOf((*httptest.ResponseRecorder)(nil)),
		"Server": reflect.ValueOf((*httptest.Server)(nil)),
	}
}
