// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/textproto"
	"reflect"
)

func init() {
	Values["net/textproto"] = map[string]reflect.Value{
		"CanonicalMIMEHeaderKey": reflect.ValueOf(textproto.CanonicalMIMEHeaderKey),
		"Dial": reflect.ValueOf(textproto.Dial),
		"TrimBytes": reflect.ValueOf(textproto.TrimBytes),
		"TrimString": reflect.ValueOf(textproto.TrimString),
		"Conn": reflect.ValueOf((*textproto.Conn)(nil)),
		"Error": reflect.ValueOf((*textproto.Error)(nil)),
		"MIMEHeader": reflect.ValueOf((*textproto.MIMEHeader)(nil)),
		"Pipeline": reflect.ValueOf((*textproto.Pipeline)(nil)),
		"ProtocolError": reflect.ValueOf((*textproto.ProtocolError)(nil)),
		"Reader": reflect.ValueOf((*textproto.Reader)(nil)),
		"Writer": reflect.ValueOf((*textproto.Writer)(nil)),
	}
}
