// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/smtp"
	"reflect"
)

func init() {
	Values["net/smtp"] = map[string]reflect.Value{
		"CRAMMD5Auth": reflect.ValueOf(smtp.CRAMMD5Auth),
		"Dial": reflect.ValueOf(smtp.Dial),
		"PlainAuth": reflect.ValueOf(smtp.PlainAuth),
		"SendMail": reflect.ValueOf(smtp.SendMail),
		"Auth": reflect.ValueOf((*smtp.Auth)(nil)),
		"Client": reflect.ValueOf((*smtp.Client)(nil)),
		"ServerInfo": reflect.ValueOf((*smtp.ServerInfo)(nil)),
	}
}
