// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/cookiejar"
	"reflect"
)

func init() {
	Values["net/http/cookiejar"] = map[string]reflect.Value{
		"New": reflect.ValueOf(cookiejar.New),
		"Jar": reflect.ValueOf((*cookiejar.Jar)(nil)),
		"Options": reflect.ValueOf((*cookiejar.Options)(nil)),
		"PublicSuffixList": reflect.ValueOf((*cookiejar.PublicSuffixList)(nil)),
	}
}
