// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/httptest"
	"reflect"
)

func init() {
	Values["net/http/httptest"] = map[string]reflect.Value{
		"DefaultRemoteAddr": reflect.ValueOf(httptest.DefaultRemoteAddr),
		"NewRecorder": reflect.ValueOf(httptest.NewRecorder),
		"NewRequest": reflect.ValueOf(httptest.NewRequest),
		"NewRequestWithContext": reflect.ValueOf(httptest.NewRequestWithContext),
		"NewServer": reflect.ValueOf(httptest.NewServer),
		"NewTLSServer": reflect.ValueOf(httptest.NewTLSServer),
		"NewUnstartedServer": reflect.ValueOf(httptest.NewUnstartedServer),
		"ResponseRecorder": reflect.ValueOf((*httptest.ResponseRecorder)(nil)),
		"Server": reflect.ValueOf((*httptest.Server)(nil)),
	}
}
