// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/httputil"
	"reflect"
)

func init() {
	Values["net/http/httputil"] = map[string]reflect.Value{
		"ErrClosed": reflect.ValueOf(&httputil.ErrClosed),
		"ErrLineTooLong": reflect.ValueOf(&httputil.ErrLineTooLong),
		"ErrPersistEOF": reflect.ValueOf(&httputil.ErrPersistEOF),
		"ErrPipeline": reflect.ValueOf(&httputil.ErrPipeline),
		"BufferPool": reflect.ValueOf((*httputil.BufferPool)(nil)),
		"ClientConn": reflect.ValueOf((*httputil.ClientConn)(nil)),
		"ProxyRequest": reflect.ValueOf((*httputil.ProxyRequest)(nil)),
		"ReverseProxy": reflect.ValueOf((*httputil.ReverseProxy)(nil)),
		"ServerConn": reflect.ValueOf((*httputil.ServerConn)(nil)),
	}
}
