// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/http/fcgi"
	"reflect"
)

func init() {
	Values["net/http/fcgi"] = map[string]reflect.Value{
		"ErrConnClosed": reflect.ValueOf(&fcgi.ErrConnClosed),
		"ErrRequestAborted": reflect.ValueOf(&fcgi.ErrRequestAborted),
	}
}
