// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"net/rpc"
	"reflect"
)

func init() {
	Values["net/rpc"] = map[string]reflect.Value{
		"Accept": reflect.ValueOf(rpc.Accept),
		"DefaultDebugPath": reflect.ValueOf(rpc.DefaultDebugPath),
		"DefaultRPCPath": reflect.ValueOf(rpc.DefaultRPCPath),
		"Dial": reflect.ValueOf(rpc.Dial),
		"DialHTTP": reflect.ValueOf(rpc.DialHTTP),
		"DialHTTPPath": reflect.ValueOf(rpc.DialHTTPPath),
		"HandleHTTP": reflect.ValueOf(rpc.HandleHTTP),
		"NewClient": reflect.ValueOf(rpc.NewClient),
		"NewClientWithCodec": reflect.ValueOf(rpc.NewClientWithCodec),
		"NewServer": reflect.ValueOf(rpc.NewServer),
		"Register": reflect.ValueOf(rpc.Register),
		"RegisterName": reflect.ValueOf(rpc.RegisterName),
		"ServeCodec": reflect.ValueOf(rpc.ServeCodec),
		"ServeConn": reflect.ValueOf(rpc.ServeConn),
		"ServeRequest": reflect.ValueOf(rpc.ServeRequest),
		"DefaultServer": reflect.ValueOf(&rpc.DefaultServer),
		"ErrShutdown": reflect.ValueOf(&rpc.ErrShutdown),
		"Call": reflect.ValueOf((*rpc.Call)(nil)),
		"Client": reflect.ValueOf((*rpc.Client)(nil)),
		"ClientCodec": reflect.ValueOf((*rpc.ClientCodec)(nil)),
		"Request": reflect.ValueOf((*rpc.Request)(nil)),
		"Response": reflect.ValueOf((*rpc.Response)(nil)),
		"Server": reflect.ValueOf((*rpc.Server)(nil)),
		"ServerCodec": reflect.ValueOf((*rpc.ServerCodec)(nil)),
		"ServerError": reflect.ValueOf((*rpc.ServerError)(nil)),
	}
}
