// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"os/exec"
	"reflect"
)

func init() {
	Values["os/exec"] = map[string]reflect.Value{
		"Command": reflect.ValueOf(exec.Command),
		"LookPath": reflect.ValueOf(exec.LookPath),
		"ErrDot": reflect.ValueOf(&exec.ErrDot),
		"ErrNotFound": reflect.ValueOf(&exec.ErrNotFound),
		"ErrWaitDelay": reflect.ValueOf(&exec.ErrWaitDelay),
		"Cmd": reflect.ValueOf((*exec.Cmd)(nil)),
		"Error": reflect.ValueOf((*exec.Error)(nil)),
		"ExitError": reflect.ValueOf((*exec.ExitError)(nil)),
	}
}
