// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"os/signal"
	"reflect"
)

func init() {
	Values["os/signal"] = map[string]reflect.Value{
		"Ignore": reflect.ValueOf(signal.Ignore),
		"Ignored": reflect.ValueOf(signal.Ignored),
		"Notify": reflect.ValueOf(signal.Notify),
		"NotifyContext": reflect.ValueOf(signal.NotifyContext),
		"Reset": reflect.ValueOf(signal.Reset),
		"Stop": reflect.ValueOf(signal.Stop),
	}
}
