// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"os/user"
	"reflect"
)

func init() {
	Values["os/user"] = map[string]reflect.Value{
		"Current": reflect.ValueOf(user.Current),
		"Lookup": reflect.ValueOf(user.Lookup),
		"LookupGroup": reflect.ValueOf(user.LookupGroup),
		"LookupGroupId": reflect.ValueOf(user.LookupGroupId),
		"LookupId": reflect.ValueOf(user.LookupId),
		"Group": reflect.ValueOf((*user.Group)(nil)),
		"UnknownGroupError": reflect.ValueOf((*user.UnknownGroupError)(nil)),
		"UnknownGroupIdError": reflect.ValueOf((*user.UnknownGroupIdError)(nil)),
		"UnknownUserError": reflect.ValueOf((*user.UnknownUserError)(nil)),
		"UnknownUserIdError": reflect.ValueOf((*user.UnknownUserIdError)(nil)),
		"User": reflect.ValueOf((*user.User)(nil)),
	}
}
