// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"path/filepath"
	"reflect"
)

func init() {
	Values["path/filepath"] = map[string]reflect.Value{
		"Abs": reflect.ValueOf(filepath.Abs),
		"Base": reflect.ValueOf(filepath.Base),
		"Clean": reflect.ValueOf(filepath.Clean),
		"Dir": reflect.ValueOf(filepath.Dir),
		"EvalSymlinks": reflect.ValueOf(filepath.EvalSymlinks),
		"Ext": reflect.ValueOf(filepath.Ext),
		"FromSlash": reflect.ValueOf(filepath.FromSlash),
		"Glob": reflect.ValueOf(filepath.Glob),
		"HasPrefix": reflect.ValueOf(filepath.HasPrefix),
		"IsAbs": reflect.ValueOf(filepath.IsAbs),
		"IsLocal": reflect.ValueOf(filepath.IsLocal),
		"Join": reflect.ValueOf(filepath.Join),
		"Localize": reflect.ValueOf(filepath.Localize),
		"Match": reflect.ValueOf(filepath.Match),
		"Rel": reflect.ValueOf(filepath.Rel),
		"Separator": reflect.ValueOf(filepath.Separator),
		"Split": reflect.ValueOf(filepath.Split),
		"SplitList": reflect.ValueOf(filepath.SplitList),
		"ToSlash": reflect.ValueOf(filepath.ToSlash),
		"VolumeName": reflect.ValueOf(filepath.VolumeName),
		"Walk": reflect.ValueOf(filepath.Walk),
		"WalkDir": reflect.ValueOf(filepath.WalkDir),
		"ErrBadPattern": reflect.ValueOf(&filepath.ErrBadPattern),
		"SkipAll": reflect.ValueOf(&filepath.SkipAll),
		"SkipDir": reflect.ValueOf(&filepath.SkipDir),
		"WalkFunc": reflect.ValueOf((*filepath.WalkFunc)(nil)),
	}
}
