// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"path"
	"reflect"
)

func init() {
	Values["path"] = map[string]reflect.Value{
		"Base": reflect.ValueOf(path.Base),
		"Clean": reflect.ValueOf(path.Clean),
		"Dir": reflect.ValueOf(path.Dir),
		"Ext": reflect.ValueOf(path.Ext),
		"IsAbs": reflect.ValueOf(path.IsAbs),
		"Join": reflect.ValueOf(path.Join),
		"Match": reflect.ValueOf(path.Match),
		"Split": reflect.ValueOf(path.Split),
		"ErrBadPattern": reflect.ValueOf(&path.ErrBadPattern),
	}
}
