// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/debug"
	"reflect"
)

func init() {
	Values["runtime/debug"] = map[string]reflect.Value{
		"FreeOSMemory": reflect.ValueOf(debug.FreeOSMemory),
		"ParseBuildInfo": reflect.ValueOf(debug.ParseBuildInfo),
		"PrintStack": reflect.ValueOf(debug.PrintStack),
		"ReadBuildInfo": reflect.ValueOf(debug.ReadBuildInfo),
		"ReadGCStats": reflect.ValueOf(debug.ReadGCStats),
		"SetGCPercent": reflect.ValueOf(debug.SetGCPercent),
		"SetMaxStack": reflect.ValueOf(debug.SetMaxStack),
		"SetMaxThreads": reflect.ValueOf(debug.SetMaxThreads),
		"SetMemoryLimit": reflect.ValueOf(debug.SetMemoryLimit),
		"SetPanicOnFault": reflect.ValueOf(debug.SetPanicOnFault),
		"Stack": reflect.ValueOf(debug.Stack),
		"BuildInfo": reflect.ValueOf((*debug.BuildInfo)(nil)),
		"BuildSetting": reflect.ValueOf((*debug.BuildSetting)(nil)),
		"CrashOptions": reflect.ValueOf((*debug.CrashOptions)(nil)),
		"GCStats": reflect.ValueOf((*debug.GCStats)(nil)),
		"Module": reflect.ValueOf((*debug.Module)(nil)),
	}
}
