// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/coverage"
	"reflect"
)

func init() {
	Values["runtime/coverage"] = map[string]reflect.Value{
		"ClearCounters": reflect.ValueOf(coverage.ClearCounters),
		"WriteCountersDir": reflect.ValueOf(coverage.WriteCountersDir),
		"WriteMetaDir": reflect.ValueOf(coverage.WriteMetaDir),
	}
}
