// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/pprof"
	"reflect"
)

func init() {
	Values["runtime/pprof"] = map[string]reflect.Value{
		"Do": reflect.ValueOf(pprof.Do),
		"ForLabels": reflect.ValueOf(pprof.ForLabels),
		"Label": reflect.ValueOf(pprof.Label),
		"Labels": reflect.ValueOf(pprof.Labels),
		"Lookup": reflect.ValueOf(pprof.Lookup),
		"NewProfile": reflect.ValueOf(pprof.NewProfile),
		"Profiles": reflect.ValueOf(pprof.Profiles),
		"SetGoroutineLabels": reflect.ValueOf(pprof.SetGoroutineLabels),
		"StartCPUProfile": reflect.ValueOf(pprof.StartCPUProfile),
		"StopCPUProfile": reflect.ValueOf(pprof.StopCPUProfile),
		"WithLabels": reflect.ValueOf(pprof.WithLabels),
		"WriteHeapProfile": reflect.ValueOf(pprof.WriteHeapProfile),
		"LabelSet": reflect.ValueOf((*pprof.LabelSet)(nil)),
		"Profile": reflect.ValueOf((*pprof.Profile)(nil)),
	}
}
