// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/pprof"
	"reflect"
)

func init() {
	Values["runtime/pprof"] = map[string]reflect.Value{
		"Labels": reflect.ValueOf(pprof.Labels),
		"Lookup": reflect.ValueOf(pprof.Lookup),
		"NewProfile": reflect.ValueOf(pprof.NewProfile),
		"Profiles": reflect.ValueOf(pprof.Profiles),
		"StopCPUProfile": reflect.ValueOf(pprof.StopCPUProfile),
		"LabelSet": reflect.ValueOf((*pprof.LabelSet)(nil)),
		"Profile": reflect.ValueOf((*pprof.Profile)(nil)),
	}
}
