// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/trace"
	"reflect"
)

func init() {
	Values["runtime/trace"] = map[string]reflect.Value{
		"IsEnabled": reflect.ValueOf(trace.IsEnabled),
		"NewFlightRecorder": reflect.ValueOf(trace.NewFlightRecorder),
		"Stop": reflect.ValueOf(trace.Stop),
		"FlightRecorder": reflect.ValueOf((*trace.FlightRecorder)(nil)),
		"FlightRecorderConfig": reflect.ValueOf((*trace.FlightRecorderConfig)(nil)),
		"Region": reflect.ValueOf((*trace.Region)(nil)),
		"Task": reflect.ValueOf((*trace.Task)(nil)),
	}
}
