// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime"
	"reflect"
)

func init() {
	Values["runtime"] = map[string]reflect.Value{
		"BlockProfile": reflect.ValueOf(runtime.BlockProfile),
		"Breakpoint": reflect.ValueOf(runtime.Breakpoint),
		"CPUProfile": reflect.ValueOf(runtime.CPUProfile),
		"Compiler": reflect.ValueOf(runtime.Compiler),
		"GC": reflect.ValueOf(runtime.GC),
		"GOARCH": reflect.ValueOf(runtime.GOARCH),
		"GOMAXPROCS": reflect.ValueOf(runtime.GOMAXPROCS),
		"GOOS": reflect.ValueOf(runtime.GOOS),
		"GOROOT": reflect.ValueOf(runtime.GOROOT),
		"Goexit": reflect.ValueOf(runtime.Goexit),
		"GoroutineProfile": reflect.ValueOf(runtime.GoroutineProfile),
		"Gosched": reflect.ValueOf(runtime.Gosched),
		"KeepAlive": reflect.ValueOf(runtime.KeepAlive),
		"LockOSThread": reflect.ValueOf(runtime.LockOSThread),
		"MemProfile": reflect.ValueOf(runtime.MemProfile),
		"MutexProfile": reflect.ValueOf(runtime.MutexProfile),
		"NumCPU": reflect.ValueOf(runtime.NumCPU),
		"NumCgoCall": reflect.ValueOf(runtime.NumCgoCall),
		"NumGoroutine": reflect.ValueOf(runtime.NumGoroutine),
		"ReadMemStats": reflect.ValueOf(runtime.ReadMemStats),
		"ReadTrace": reflect.ValueOf(runtime.ReadTrace),
		"SetBlockProfileRate": reflect.ValueOf(runtime.SetBlockProfileRate),
		"SetCPUProfileRate": reflect.ValueOf(runtime.SetCPUProfileRate),
		"SetCgoTraceback": reflect.ValueOf(runtime.SetCgoTraceback),
		"SetDefaultGOMAXPROCS": reflect.ValueOf(runtime.SetDefaultGOMAXPROCS),
		"SetFinalizer": reflect.ValueOf(runtime.SetFinalizer),
		"SetMutexProfileFraction": reflect.ValueOf(runtime.SetMutexProfileFraction),
		"Stack": reflect.ValueOf(runtime.Stack),
		"StartTrace": reflect.ValueOf(runtime.StartTrace),
		"StopTrace": reflect.ValueOf(runtime.StopTrace),
		"ThreadCreateProfile": reflect.ValueOf(runtime.ThreadCreateProfile),
		"UnlockOSThread": reflect.ValueOf(runtime.UnlockOSThread),
		"Version": reflect.ValueOf(runtime.Version),
		"MemProfileRate": reflect.ValueOf(&runtime.MemProfileRate),
		"BlockProfileRecord": reflect.ValueOf((*runtime.BlockProfileRecord)(nil)),
		"Cleanup": reflect.ValueOf((*runtime.Cleanup)(nil)),
		"Error": reflect.ValueOf((*runtime.Error)(nil)),
		"Frame": reflect.ValueOf((*runtime.Frame)(nil)),
		"Frames": reflect.ValueOf((*runtime.Frames)(nil)),
		"Func": reflect.ValueOf((*runtime.Func)(nil)),
		"MemProfileRecord": reflect.ValueOf((*runtime.MemProfileRecord)(nil)),
		"MemStats": reflect.ValueOf((*runtime.MemStats)(nil)),
		"PanicNilError": reflect.ValueOf((*runtime.PanicNilError)(nil)),
		"Pinner": reflect.ValueOf((*runtime.Pinner)(nil)),
		"StackRecord": reflect.ValueOf((*runtime.StackRecord)(nil)),
		"TypeAssertionError": reflect.ValueOf((*runtime.TypeAssertionError)(nil)),
	}
}
