// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"runtime/cgo"
	"reflect"
)

func init() {
	Values["runtime/cgo"] = map[string]reflect.Value{
		"Incomplete": reflect.ValueOf((*cgo.Incomplete)(nil)),
	}
}
