// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"sort"
	"reflect"
)

func init() {
	Values["sort"] = map[string]reflect.Value{
		"Find": reflect.ValueOf(sort.Find),
		"Float64s": reflect.ValueOf(sort.Float64s),
		"Float64sAreSorted": reflect.ValueOf(sort.Float64sAreSorted),
		"Ints": reflect.ValueOf(sort.Ints),
		"IntsAreSorted": reflect.ValueOf(sort.IntsAreSorted),
		"IsSorted": reflect.ValueOf(sort.IsSorted),
		"Reverse": reflect.ValueOf(sort.Reverse),
		"Search": reflect.ValueOf(sort.Search),
		"SearchFloat64s": reflect.ValueOf(sort.SearchFloat64s),
		"SearchInts": reflect.ValueOf(sort.SearchInts),
		"SearchStrings": reflect.ValueOf(sort.SearchStrings),
		"Slice": reflect.ValueOf(sort.Slice),
		"SliceIsSorted": reflect.ValueOf(sort.SliceIsSorted),
		"SliceStable": reflect.ValueOf(sort.SliceStable),
		"Sort": reflect.ValueOf(sort.Sort),
		"Stable": reflect.ValueOf(sort.Stable),
		"Strings": reflect.ValueOf(sort.Strings),
		"StringsAreSorted": reflect.ValueOf(sort.StringsAreSorted),
		"Float64Slice": reflect.ValueOf((*sort.Float64Slice)(nil)),
		"IntSlice": reflect.ValueOf((*sort.IntSlice)(nil)),
		"Interface": reflect.ValueOf((*sort.Interface)(nil)),
		"StringSlice": reflect.ValueOf((*sort.StringSlice)(nil)),
	}
}
