// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"structs"
	"reflect"
)

func init() {
	Values["structs"] = map[string]reflect.Value{
		"HostLayout": reflect.ValueOf((*structs.HostLayout)(nil)),
	}
}
