// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"sync"
	"reflect"
)

func init() {
	Values["sync"] = map[string]reflect.Value{
		"NewCond": reflect.ValueOf(sync.NewCond),
		"OnceFunc": reflect.ValueOf(sync.OnceFunc),
		"Cond": reflect.ValueOf((*sync.Cond)(nil)),
		"Locker": reflect.ValueOf((*sync.Locker)(nil)),
		"Map": reflect.ValueOf((*sync.Map)(nil)),
		"Mutex": reflect.ValueOf((*sync.Mutex)(nil)),
		"Once": reflect.ValueOf((*sync.Once)(nil)),
		"Pool": reflect.ValueOf((*sync.Pool)(nil)),
		"RWMutex": reflect.ValueOf((*sync.RWMutex)(nil)),
		"WaitGroup": reflect.ValueOf((*sync.WaitGroup)(nil)),
	}
}
