// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"sync/atomic"
	"reflect"
)

func init() {
	Values["sync/atomic"] = map[string]reflect.Value{
		"AddInt32": reflect.ValueOf(atomic.AddInt32),
		"AddInt64": reflect.ValueOf(atomic.AddInt64),
		"AddUint32": reflect.ValueOf(atomic.AddUint32),
		"AddUint64": reflect.ValueOf(atomic.AddUint64),
		"AndInt32": reflect.ValueOf(atomic.AndInt32),
		"AndInt64": reflect.ValueOf(atomic.AndInt64),
		"AndUint32": reflect.ValueOf(atomic.AndUint32),
		"AndUint64": reflect.ValueOf(atomic.AndUint64),
		"CompareAndSwapInt32": reflect.ValueOf(atomic.CompareAndSwapInt32),
		"CompareAndSwapInt64": reflect.ValueOf(atomic.CompareAndSwapInt64),
		"CompareAndSwapPointer": reflect.ValueOf(atomic.CompareAndSwapPointer),
		"CompareAndSwapUint32": reflect.ValueOf(atomic.CompareAndSwapUint32),
		"CompareAndSwapUint64": reflect.ValueOf(atomic.CompareAndSwapUint64),
		"LoadInt32": reflect.ValueOf(atomic.LoadInt32),
		"LoadInt64": reflect.ValueOf(atomic.LoadInt64),
		"LoadPointer": reflect.ValueOf(atomic.LoadPointer),
		"LoadUint32": reflect.ValueOf(atomic.LoadUint32),
		"LoadUint64": reflect.ValueOf(atomic.LoadUint64),
		"OrInt32": reflect.ValueOf(atomic.OrInt32),
		"OrInt64": reflect.ValueOf(atomic.OrInt64),
		"OrUint32": reflect.ValueOf(atomic.OrUint32),
		"OrUint64": reflect.ValueOf(atomic.OrUint64),
		"StoreInt32": reflect.ValueOf(atomic.StoreInt32),
		"StoreInt64": reflect.ValueOf(atomic.StoreInt64),
		"StorePointer": reflect.ValueOf(atomic.StorePointer),
		"StoreUint32": reflect.ValueOf(atomic.StoreUint32),
		"StoreUint64": reflect.ValueOf(atomic.StoreUint64),
		"SwapInt32": reflect.ValueOf(atomic.SwapInt32),
		"SwapInt64": reflect.ValueOf(atomic.SwapInt64),
		"SwapPointer": reflect.ValueOf(atomic.SwapPointer),
		"SwapUint32": reflect.ValueOf(atomic.SwapUint32),
		"SwapUint64": reflect.ValueOf(atomic.SwapUint64),
		"Bool": reflect.ValueOf((*atomic.Bool)(nil)),
		"Int32": reflect.ValueOf((*atomic.Int32)(nil)),
		"Int64": reflect.ValueOf((*atomic.Int64)(nil)),
		"Uint32": reflect.ValueOf((*atomic.Uint32)(nil)),
		"Uint64": reflect.ValueOf((*atomic.Uint64)(nil)),
		"Uintptr": reflect.ValueOf((*atomic.Uintptr)(nil)),
		"Value": reflect.ValueOf((*atomic.Value)(nil)),
	}
}
