// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"sync/atomic"
	"reflect"
)

func init() {
	Values["sync/atomic"] = map[string]reflect.Value{
		"Bool": reflect.ValueOf((*atomic.Bool)(nil)),
		"Int32": reflect.ValueOf((*atomic.Int32)(nil)),
		"Int64": reflect.ValueOf((*atomic.Int64)(nil)),
		"Uint32": reflect.ValueOf((*atomic.Uint32)(nil)),
		"Uint64": reflect.ValueOf((*atomic.Uint64)(nil)),
		"Uintptr": reflect.ValueOf((*atomic.Uintptr)(nil)),
		"Value": reflect.ValueOf((*atomic.Value)(nil)),
	}
}
