//go:build android && arm

// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"syscall"
	"reflect"
)

func init() {
	Values["syscall"] = map[string]reflect.Value{
		"Bind": reflect.ValueOf(syscall.Bind),
		"BytePtrFromString": reflect.ValueOf(syscall.BytePtrFromString),
		"ByteSliceFromString": reflect.ValueOf(syscall.ByteSliceFromString),
		"Clearenv": reflect.ValueOf(syscall.Clearenv),
		"CloseOnExec": reflect.ValueOf(syscall.CloseOnExec),
		"CmsgLen": reflect.ValueOf(syscall.CmsgLen),
		"CmsgSpace": reflect.ValueOf(syscall.CmsgSpace),
		"Connect": reflect.ValueOf(syscall.Connect),
		"Environ": reflect.ValueOf(syscall.Environ),
		"Exec": reflect.ValueOf(syscall.Exec),
		"ForkExec": reflect.ValueOf(syscall.ForkExec),
		"Getenv": reflect.ValueOf(syscall.Getenv),
		"Getpeername": reflect.ValueOf(syscall.Getpeername),
		"GetsockoptInt": reflect.ValueOf(syscall.GetsockoptInt),
		"ParseDirent": reflect.ValueOf(syscall.ParseDirent),
		"ParseSocketControlMessage": reflect.ValueOf(syscall.ParseSocketControlMessage),
		"ParseUnixRights": reflect.ValueOf(syscall.ParseUnixRights),
		"Pread": reflect.ValueOf(syscall.Pread),
		"Pwrite": reflect.ValueOf(syscall.Pwrite),
		"Read": reflect.ValueOf(syscall.Read),
		"Recvfrom": reflect.ValueOf(syscall.Recvfrom),
		"Recvmsg": reflect.ValueOf(syscall.Recvmsg),
		"Sendfile": reflect.ValueOf(syscall.Sendfile),
		"Sendmsg": reflect.ValueOf(syscall.Sendmsg),
		"SendmsgN": reflect.ValueOf(syscall.SendmsgN),
		"Sendto": reflect.ValueOf(syscall.Sendto),
		"SetNonblock": reflect.ValueOf(syscall.SetNonblock),
		"Setenv": reflect.ValueOf(syscall.Setenv),
		"SetsockoptByte": reflect.ValueOf(syscall.SetsockoptByte),
		"SetsockoptInet4Addr": reflect.ValueOf(syscall.SetsockoptInet4Addr),
		"SetsockoptInt": reflect.ValueOf(syscall.SetsockoptInt),
		"SetsockoptString": reflect.ValueOf(syscall.SetsockoptString),
		"SlicePtrFromStrings": reflect.ValueOf(syscall.SlicePtrFromStrings),
		"Socket": reflect.ValueOf(syscall.Socket),
		"Socketpair": reflect.ValueOf(syscall.Socketpair),
		"StringBytePtr": reflect.ValueOf(syscall.StringBytePtr),
		"StringByteSlice": reflect.ValueOf(syscall.StringByteSlice),
		"StringSlicePtr": reflect.ValueOf(syscall.StringSlicePtr),
		"UnixRights": reflect.ValueOf(syscall.UnixRights),
		"Unsetenv": reflect.ValueOf(syscall.Unsetenv),
		"Write": reflect.ValueOf(syscall.Write),
		"ForkLock": reflect.ValueOf(&syscall.ForkLock),
		"SocketDisableIPv6": reflect.ValueOf(&syscall.SocketDisableIPv6),
		"Stderr": reflect.ValueOf(&syscall.Stderr),
		"Stdin": reflect.ValueOf(&syscall.Stdin),
		"Stdout": reflect.ValueOf(&syscall.Stdout),
		"Conn": reflect.ValueOf((*syscall.Conn)(nil)),
		"Credential": reflect.ValueOf((*syscall.Credential)(nil)),
		"ProcAttr": reflect.ValueOf((*syscall.ProcAttr)(nil)),
		"RawConn": reflect.ValueOf((*syscall.RawConn)(nil)),
		"Signal": reflect.ValueOf((*syscall.Signal)(nil)),
		"Sockaddr": reflect.ValueOf((*syscall.Sockaddr)(nil)),
		"SockaddrInet4": reflect.ValueOf((*syscall.SockaddrInet4)(nil)),
		"SockaddrInet6": reflect.ValueOf((*syscall.SockaddrInet6)(nil)),
		"SockaddrUnix": reflect.ValueOf((*syscall.SockaddrUnix)(nil)),
		"SocketControlMessage": reflect.ValueOf((*syscall.SocketControlMessage)(nil)),
	}
}
