// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing/iotest"
	"reflect"
)

func init() {
	Values["testing/iotest"] = map[string]reflect.Value{
		"ErrTimeout": reflect.ValueOf(&iotest.ErrTimeout),
	}
}
