// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing/iotest"
	"reflect"
)

func init() {
	Values["testing/iotest"] = map[string]reflect.Value{
		"DataErrReader": reflect.ValueOf(iotest.DataErrReader),
		"ErrReader": reflect.ValueOf(iotest.ErrReader),
		"HalfReader": reflect.ValueOf(iotest.HalfReader),
		"NewReadLogger": reflect.ValueOf(iotest.NewReadLogger),
		"NewWriteLogger": reflect.ValueOf(iotest.NewWriteLogger),
		"OneByteReader": reflect.ValueOf(iotest.OneByteReader),
		"TestReader": reflect.ValueOf(iotest.TestReader),
		"TimeoutReader": reflect.ValueOf(iotest.TimeoutReader),
		"TruncateWriter": reflect.ValueOf(iotest.TruncateWriter),
		"ErrTimeout": reflect.ValueOf(&iotest.ErrTimeout),
	}
}
