// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing"
	"reflect"
)

func init() {
	Values["testing"] = map[string]reflect.Value{
		"AllocsPerRun": reflect.ValueOf(testing.AllocsPerRun),
		"Benchmark": reflect.ValueOf(testing.Benchmark),
		"CoverMode": reflect.ValueOf(testing.CoverMode),
		"Coverage": reflect.ValueOf(testing.Coverage),
		"Init": reflect.ValueOf(testing.Init),
		"Main": reflect.ValueOf(testing.Main),
		"MainStart": reflect.ValueOf(testing.MainStart),
		"RegisterCover": reflect.ValueOf(testing.RegisterCover),
		"RunBenchmarks": reflect.ValueOf(testing.RunBenchmarks),
		"RunExamples": reflect.ValueOf(testing.RunExamples),
		"RunTests": reflect.ValueOf(testing.RunTests),
		"Short": reflect.ValueOf(testing.Short),
		"Testing": reflect.ValueOf(testing.Testing),
		"Verbose": reflect.ValueOf(testing.Verbose),
		"B": reflect.ValueOf((*testing.B)(nil)),
		"BenchmarkResult": reflect.ValueOf((*testing.BenchmarkResult)(nil)),
		"Cover": reflect.ValueOf((*testing.Cover)(nil)),
		"CoverBlock": reflect.ValueOf((*testing.CoverBlock)(nil)),
		"F": reflect.ValueOf((*testing.F)(nil)),
		"InternalBenchmark": reflect.ValueOf((*testing.InternalBenchmark)(nil)),
		"InternalExample": reflect.ValueOf((*testing.InternalExample)(nil)),
		"InternalFuzzTarget": reflect.ValueOf((*testing.InternalFuzzTarget)(nil)),
		"InternalTest": reflect.ValueOf((*testing.InternalTest)(nil)),
		"M": reflect.ValueOf((*testing.M)(nil)),
		"PB": reflect.ValueOf((*testing.PB)(nil)),
		"T": reflect.ValueOf((*testing.T)(nil)),
		"TB": reflect.ValueOf((*testing.TB)(nil)),
	}
}
