// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing/synctest"
	"reflect"
)

func init() {
	Values["testing/synctest"] = map[string]reflect.Value{
		"Test": reflect.ValueOf(synctest.Test),
		"Wait": reflect.ValueOf(synctest.Wait),
	}
}
