// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing/quick"
	"reflect"
)

func init() {
	Values["testing/quick"] = map[string]reflect.Value{
		"Check": reflect.ValueOf(quick.Check),
		"CheckEqual": reflect.ValueOf(quick.CheckEqual),
		"CheckEqualError": reflect.ValueOf((*quick.CheckEqualError)(nil)),
		"CheckError": reflect.ValueOf((*quick.CheckError)(nil)),
		"Config": reflect.ValueOf((*quick.Config)(nil)),
		"Generator": reflect.ValueOf((*quick.Generator)(nil)),
		"SetupError": reflect.ValueOf((*quick.SetupError)(nil)),
	}
}
