// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"testing/fstest"
	"reflect"
)

func init() {
	Values["testing/fstest"] = map[string]reflect.Value{
		"MapFS": reflect.ValueOf((*fstest.MapFS)(nil)),
		"MapFile": reflect.ValueOf((*fstest.MapFile)(nil)),
	}
}
