// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"text/tabwriter"
	"reflect"
)

func init() {
	Values["text/tabwriter"] = map[string]reflect.Value{
		"AlignRight": reflect.ValueOf(tabwriter.AlignRight),
		"Debug": reflect.ValueOf(tabwriter.Debug),
		"DiscardEmptyColumns": reflect.ValueOf(tabwriter.DiscardEmptyColumns),
		"Escape": reflect.ValueOf(tabwriter.Escape),
		"FilterHTML": reflect.ValueOf(tabwriter.FilterHTML),
		"NewWriter": reflect.ValueOf(tabwriter.NewWriter),
		"StripEscape": reflect.ValueOf(tabwriter.StripEscape),
		"TabIndent": reflect.ValueOf(tabwriter.TabIndent),
		"Writer": reflect.ValueOf((*tabwriter.Writer)(nil)),
	}
}
