// Code generated by cmd/extract; DO NOT EDIT.

package stdlib

import (
	"unicode/utf8"
	"reflect"
)

func init() {
	Values["unicode/utf8"] = map[string]reflect.Value{
		"AppendRune": reflect.ValueOf(utf8.AppendRune),
		"DecodeLastRune": reflect.ValueOf(utf8.DecodeLastRune),
		"DecodeLastRuneInString": reflect.ValueOf(utf8.DecodeLastRuneInString),
		"DecodeRune": reflect.ValueOf(utf8.DecodeRune),
		"DecodeRuneInString": reflect.ValueOf(utf8.DecodeRuneInString),
		"EncodeRune": reflect.ValueOf(utf8.EncodeRune),
		"FullRune": reflect.ValueOf(utf8.FullRune),
		"FullRuneInString": reflect.ValueOf(utf8.FullRuneInString),
		"MaxRune": reflect.ValueOf(utf8.MaxRune),
		"RuneCount": reflect.ValueOf(utf8.RuneCount),
		"RuneCountInString": reflect.ValueOf(utf8.RuneCountInString),
		"RuneError": reflect.ValueOf(utf8.RuneError),
		"RuneLen": reflect.ValueOf(utf8.RuneLen),
		"RuneSelf": reflect.ValueOf(utf8.RuneSelf),
		"RuneStart": reflect.ValueOf(utf8.RuneStart),
		"UTFMax": reflect.ValueOf(utf8.UTFMax),
		"Valid": reflect.ValueOf(utf8.Valid),
		"ValidRune": reflect.ValueOf(utf8.ValidRune),
		"ValidString": reflect.ValueOf(utf8.ValidString),
	}
}
