// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package symbol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Value-0]
	_ = x[Type-1]
	_ = x[Label-2]
	_ = x[Const-3]
	_ = x[Var-4]
	_ = x[Func-5]
	_ = x[Pkg-6]
}

const _Kind_name = "ValueTypeLabelConstVarFuncPkg"

var _Kind_index = [...]uint8{0, 5, 9, 14, 19, 22, 26, 29}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
