// Code generated by "stringer -type=symKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[symValue-0]
	_ = x[symType-1]
	_ = x[symLabel-2]
	_ = x[symConst-3]
	_ = x[symVar-4]
	_ = x[symFunc-5]
	_ = x[symPkg-6]
}

const _symKind_name = "symValuesymTypesymLabelsymConstsymVarsymFuncsymPkg"

var _symKind_index = [...]uint8{0, 8, 15, 23, 31, 37, 44, 50}

func (i symKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_symKind_index)-1 {
		return "symKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _symKind_name[_symKind_index[idx]:_symKind_index[idx+1]]
}
