// Code generated by "stringer -type=SymKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymValue-0]
	_ = x[SymType-1]
	_ = x[SymLabel-2]
	_ = x[SymConst-3]
	_ = x[SymVar-4]
	_ = x[SymFunc-5]
	_ = x[SymPkg-6]
}

const _SymKind_name = "SymValueSymTypeSymLabelSymConstSymVarSymFuncSymPkg"

var _SymKind_index = [...]uint8{0, 8, 15, 23, 31, 37, 44, 50}

func (i SymKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SymKind_index)-1 {
		return "SymKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymKind_name[_SymKind_index[idx]:_SymKind_index[idx+1]]
}
